### ISSUE TITLE
Need for manual scan: Multi-device & Multi-network

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#10]
Tonight, I tried the app at another location (where we have two Integras on the network).  The app kept trying to connect to the IP address of my receiver at home.

For scenarios like this I think the following would be useful:

1. Ability to manually force a scan for receivers
2. Ability to select a receiver when multiple receivers are on the network
3. Ability to save and/or pick a default receiver on the network.

**Comment by mkulesh** [comment]
Hi @mrlad, the app is already able  to manually force a scan for receivers. It is the button "Device" on DEVICE tab:
![device_search](https://user-images.githubusercontent.com/30557348/52169370-483aac00-2737-11e9-9322-53bd597005c8.png)

It is possible to implement receiver selection and default receiver settings as some callbacks from AsyncTask BroadcastSearch. Unfortunately, I have no possibility to test this functionality sine I have only one Integra device. Therefore, I can implement it, but it will take more time. Do you have any Android experience in order to help me implement this feature?

**Comment by mrlad** [comment]
Also, now that I know about the scan option, I've been able to use it to rescan and find receivers.  Its just not obvious to me that pressing the magnifying glass will force a search.

**Comment by mkulesh** [comment]
Hi @mrlad, I added multi-device search. Now, if you press "Search device" button (the magnifying glass) on the DEVICE tab, the "Search device" dialog appears. The same dialog also appears if the application is started at the first time. The app sends broadcast requests and collects Onkyo responses with 3 sec. frequency until the button "CANCEL" or any found device from device list will be pressed. Could you please test whether the app correctly collects all devices from you network? And a question: what do you mean with "Multi-network" scan? I currently send broadcast to 255.255.255.255 subnet. I am not sure whether it is meaningful...

The dialog looks like this:
![device_search](https://user-images.githubusercontent.com/30557348/52445290-faed7e80-2b2a-11e9-9cf9-a27ae5b5bdb9.png)

**Comment by mkulesh** [comment]
If this prototype works, I can store all found devices and add them into the navigation drawer as you suggested in other issue. However, in this scan mode friendly device names may be not available since the broadcast response only contains the following data: model name of device, ISCP port number, destination area of device (US, EU, Asia, etc) and an unique Identifier. Which data do you prefer to see in the navigation drawer?

**Comment by mrlad** [comment]
_what do you mean with "Multi-network" scan?_

Sorry, typo.  Meant multi-device scan.

_Which data do you prefer to see in the navigation drawer?_

I'd prefer to see the Friendly name that you obtained previously.  Failing that, then the model name.

To be clear though, when the Nav draw opens a scan shouldn't be done automatically.  Only scan upon request.

I will test out either tomorrow or this weekend as on my home network I only have on Integra receiver.

**Comment by mkulesh** [comment]
Hi @mrlad, 
now I moved search and connection buttons from the DEVICE tab into the navigation drawer. I thing connection functionality logically belongs to the navigation drawer instead of a device information tab.
That do you think about this design?

![navigation_drawer](https://user-images.githubusercontent.com/30557348/52507058-c3e1a080-2bf0-11e9-90c3-59f36d01fff8.png)

**Comment by mrlad** [comment]
I like the way this looks!  Nice design.

**Comment by mrlad** [comment]
I tested it out the subnet broadcast for multiple devices this weekend:

It correctly identified the two receivers on the network and I was able to select each device.

There is a bug however.  The media Inputs (NET, CD, Bluray etc.) aren't refreshed when the device changes.

**Comment by mkulesh** [comment]
Hi @mrlad, thanks for testing. I found the bug related to the refreshing of media inputs and fixed it.

**Comment by mkulesh** [comment]
Released in v0.7

**Comment by mrlad** [comment]
I like your implementation.  Confirmed functional and fixed.
