### ISSUE TITLE
Search doesn't always show the friendly name

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#104]
When I search for devices, sometimes a friendly name is shown, sometimes I just see the IP address.  I haven't detected a repeatable pattern yet.  Seems random right now.

**Comment by mkulesh** [comment]
If you observe such a behavior again, could you please take a screenshot and immoderately close the search dialog by pressing CANCEL button, open "About" from the navigation drawer, open the tab LATEST LOG, long press on the text, than "Select all", than "Copy" and email it to me together with the screenshot?

**Comment by mrlad** [comment]
I might have a hint as to what's going on.

One time I saw the IP address show in the search and about 2-3 seconds later it was replaced by the friendly name.

**Comment by mkulesh** [comment]
Hi @mrlad,
this delayed update of the friendly name is a desired behavior. The reason is that IP address is taken from a broadcast response message. This is the first response message obtained when a remote device is discovered. On this event, the IP address appears in the list of found devices, the app establishes a connection to this device and sends a couple of requests like multi-room state information and friendly name request.  The response of these request can reach the app with a couple of seconds delay. Of course I can introduce a timer (for example 2 or 3 seconds) and only show the device after this threshold in the list of found devices (hope that friendly name response appears within this interval). However, the situation when this response will need more time still be possible and such a timer does not solve the problem in any cases. How do you think?

**Comment by mrlad** [comment]
Hi @mkulesh ,

I understand now.  If no friendly name is received, showing the IP address is the right solution.  Unless you were to show both the IP address and the friendly name for the receiver.  In which case you could put <IP address><Friendly Name>.  When its received you'd put both.  When its not, just the IP address.

**Comment by mkulesh** [comment]
Released in iOS version 2.1.1
