### ISSUE TITLE
Remote device not responding

### ISSUE THREAD

**Issue by mareking** [mkulesh/onpc#108]
Android Device: LG G6 with LineageOS 15.1 (Android 8 Oreo)
Build: 1.7 build retrieved 18.12.2019

Main issue: no connection to Onkyo receiver possible
error message: "Remote device not responding"

When I start the app the white "search window" appears in the foreground with no entry. I can only press cancel there. Then if I don't do anything after a few seconds the window disappears and an error message ("No connection to Wi-Fi. Please input remote device IP and port manually") is shown. Very similar to issue #95 

When I try to connect manually with the correct IP address and the (predefined) port 60128 I receive the error message: "Remote device 123.456.789.0 is not responding". (Of course I used the correct IP address and chose 123.456.789.0 for illustration purposes only!)

Via its correct IP address I can reach the Onkyo receiver in the browser without any issues.

![enhanced-controller-screenshot-no-connection](https://user-images.githubusercontent.com/34281885/71218510-09b3ce80-22c2-11ea-80de-6f47976d86c5.png)
![enhanced-controller-screenshot-not-responding](https://user-images.githubusercontent.com/34281885/71218511-09b3ce80-22c2-11ea-840b-d5e4702ced5d.png)
![enhanced-controller-screenshot-search-cancel](https://user-images.githubusercontent.com/34281885/71218512-09b3ce80-22c2-11ea-8754-1a57d2f6b97f.png)

**Comment by mkulesh** [comment]
Hi @mareking,
thank you for submitting issue. I believe I have a similar report in the issue list: https://github.com/mkulesh/onpc/issues/82

There can be following reasons for such a problem:
1. Which receiver model do you have? My app supports so called ISCP protocol only. Some Onkyo models, however, support only DLNA protocol (like C-N7050 reported in https://github.com/mkulesh/onpc/issues/82). My app will not work with such a devices. If you have any programming skills, please feel free to join the development and help me to implement DLNA support.
2. Some people reported that Onkyo device works sometime unstable if connected via WiFi. If you currently use wireless connection, could you please try to re-connect your receiver via Ethernet cable instead of WiFi?
3. Some people also reported that Onkyo device was not responding like in your case, but factory reset can solve the problem.

**Comment by mareking** [comment]
Hey @mkulesh,
thanks for your reply. Resetting was indeed the solution!

1. It is a TX-NR509 which is explicitly supported, right? In version 1.7: "Allow subwoofer and center level for TX-NR509".
2. The receiver is directly connected to the router via LAN cable. The Smartphone is connected via WiFi of course.
3. THE SOLUTION: Resetting the receiver (keep pressing both ON/STANDBY and VCR/DVR buttons, then plugin the power cable) enabled the app to find it immediately.

**Comment by mkulesh** [comment]
Hi @mareking,
thank you for feedback. It is the second case where resetting of the receiver fixes the problem that the receiver does not answers network request. It seems to be firmware works slightly unstable. I suggest to check whether a new receiver firmware is available and install it if firmware update exists.
