### ISSUE TITLE
Volume level off by 2x

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#11]
The volume level in zone 1 and zone 2 are off by a factor of two.

I'm testing with an Integra DRX 5.2 if it makes any difference.

**Comment by mkulesh** [comment]
Hi @mrlad, thank you for observation. I am totally confused with the documentation of volume level. The protocol description has following description of volume level:
"00"-"C8" | Volume Level 0.0 – 100.0 ( 0.5 Step In hexadecimal representation)
"00"-"64" | Volume Level 0 – 100 ( In hexadecimal representation)
"00"-"50" | Volume Level 0 – 80 ( In hexadecimal representation)
"00"-"32" | Volume Level 0 – 50 ( In hexadecimal representation)
Currently, I just show the decimal value of the hexadecimal level obtained from receiver. 

On the other hand, the receiver information also has a parameter "volmax" for each available zone:
For example, for TX-NR676E it is:
        <zonelist count="4">
            <zone id="1" value="1" name="Main" volmax="82" volstep="1" src="1" dst="1"
                lrselect="0" />
            <zone id="2" value="1" name="Zone2" volmax="0" volstep="1" src="0" dst="0"
                lrselect="0" />
            <zone id="3" value="0" name="Zone3" volmax="0" volstep="0" src="0" dst="0"
                lrselect="0" />
            <zone id="4" value="0" name="Zone4" volmax="0" volstep="0" src="0" dst="0"
                lrselect="0" />
        </zonelist>

This volmax does not match, however, the limits in the documentation. Do you see volume level on the receiver display or in the official Onkyo app? Do you mean this value is 2 times greater than the value shown in my app or the value from my app is two times greater then value from receiver? May be one value is related to whole steps while the other one - to 0.5 Steps? In any case it is not complicated to scale the value in the app...

**Comment by mrlad** [comment]
The official app doesn't show a level #, just a scale.  But the value shown in your app is 2x what I see on the screen when the receiver changes level.

**Comment by mrlad** [comment]
Interestingly enough, looking at the NOnkyo project (Windows Onkyo app), it also reports volume 2x what the receiver shows on screen

https://github.com/PinBack23/nonkyo/releases

**Comment by mrlad** [comment]
_May be one value is related to whole steps while the other one - to 0.5 Steps?_

When I change the volume level, the receiver increments by .5 and your app increments by 1 so that does appear to be the issue.

**Comment by mkulesh** [comment]
Hi @mrlad, thank you, your information is very helpful. I found the step setting in the receiver information message that defines how the volume is changed (by 1 dB or by 0.5 dB) and used this setting in order to divide the level show in app by 2 if receiver changes the volume by  0.5 dB. I hope it is exactly your case. Now I expect that the volume level shown in the app is equal to the level shown in your receiver. Could you please test it?

Thank for the link to https://github.com/PinBack23/nonkyo

I looked into the code and see that zone support in this project is implemented not completely, for example the zone-dependent step factor is missed. Therefore it also reports volume 2x what the receiver shows on screen.

**Comment by mkulesh** [comment]
Released in v0.7

**Comment by mrlad** [comment]
Confirmed fixed.
