### ISSUE TITLE
Implement widgets

### ISSUE THREAD

**Issue by kiikoh** [mkulesh/onpc#114]
Example could include volume up and down, or input switchers

**Comment by mkulesh** [comment]
Hi @kiikoh,
thank your for idea. Unfortunately, the internal app architecture does not allow to do it in a simple way since the app is currently a "monolith" and does not contain any background services necessary to hold the connection with a receiver. It means, there are only two options:
* Re-design the app and split in into two parts: background services and fronted. It will allow us to implement widgets that correct display the actual receiver state
* Keep existing design. In this case, a widget is not able to hold connection to the receiver and, therefore, is not able to indicate current receiver state (current switch or current volume). Such a widget is simple to implement but is not really usable. 

Currently I have no capacity to implement this feature. If you have any Android experiences and could implement it, I can help you.

**Comment by mkulesh** [comment]
Currently, no resources to implement it; nobody can help with it.

**Comment by mkulesh** [comment]
For Android Premium version only!

Added new "Playback control" widget:
![widget_playback_preview](https://github.com/mkulesh/onpc/assets/30557348/b8eb8628-a72a-4fc0-a9f7-3d7373149184)

Redesigned shortcuts widget:
![widget_shortcuts_preview](https://github.com/mkulesh/onpc/assets/30557348/7b18b680-ebb8-44c9-950e-348282f3d823)

Both widgets support different themes and background transparency that can be changed in the app settings, "Widget options" parameter section.

**Comment by mkulesh** [comment]
Released in v2.13.2 (Android only)
