### ISSUE TITLE
Empty NET items on TX-NR509 

### ISSUE THREAD

**Issue by reinouts** [mkulesh/onpc#125]
The UI shows the number of items but I cannot connect to vTuner internet radio stations. 

![Screenshot_20200208-113508](https://user-images.githubusercontent.com/1968692/74083655-186b6600-4a67-11ea-8d98-c80cf75fc4e0.png)

**Comment by mkulesh** [comment]
Hi @reinouts,

Thank you for bug report. In order to understand and solve this bug, I need the application logging. Could you please do following:

- Install the latest nightly build from here: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.9-debug.apk
- Since this build is not signed, you may need to uninstall the previous version before
- Open "Settings" dialog and activate the "Developer options" at the end of the settings list
- Go back to the app. An application menu (three dots on the right of toolbar) appears
- In the app, select vTuner internet radio as in your screenshot
- Press the application menu button and select the menu "Latest logging"
- Long press on the text and than press "Select All" from context menu
- Copy this text in buffer ("Copy" from the context menu) and send it me per e-mail (mikhail.kulesh@gmail.com)
- Open "Settings" dialog again and DISABLE the "Developer options"

I hope this log helps me to solve the problem.

**Comment by mkulesh** [comment]
Released in iOS Release 2.2
