### ISSUE TITLE
Google Home / Assistant

### ISSUE THREAD

**Issue by superflybribri** [mkulesh/onpc#136]
Are there any possibilities for Google Home / Assistant integration and voice control of the receiver via this app?

**Comment by mkulesh** [comment]
Hi @superflybribri,
thank you for the proposal. I am sorry for the delayed response on your issue since it was difficult to decide about it.

There are  both advantages and disadvantages in such a functionality.
From my point of view, there is only one advantage: voice control
But, there are a lot of disadvantages:
- Currently, the app is distributed under GPL license. I do not know any good working GPL libraries that may perform voice processing locally on the device
- The integration with Google/Apple/Amazon speech recognition services is not a good solution since these companies do not respect any privacy that is con consistent with the app philosophy.
- The last point is the reason why I do not have and will not use any devices with speech recognition functionality. It means, I have and will not have any hardware to debug and test it.
- Currently, I develop the app alone. In order to implement this functionality, a huge effort is necessary. It is not realistic for a single developer.

Therefore, I put the issue in state "Help wanted" for a half of year. If somebody will implement this functionality, I will support it.

**Comment by mkulesh** [comment]
It is now possible to configure voice control using the "Tasker" app, see #184. Therefore, this issue is obsolete and closed.
