### ISSUE TITLE
TuneIn Streams

### ISSUE THREAD

**Issue by rolli51** [mkulesh/onpc#137]
When I select a Tunein Station and start playing, the first stream is used. Some Streams are yery bad. So I can Select another stream which is better.. 
But when the playing is stopped (or the station is  saved in presets), on next start the first stream is selected.
Is it possible to save the streamselection in station presets, when saved and for replay in the session?

kind regards Roland

**Comment by mkulesh** [comment]
Hi @rolli51 
The station menu that you see for Tunein Station is really generic object. Unfortunately, there is no command that means "select the stream number one (or two, or three...)". The app sends to the receiver that user selected station menu mode. The receiver answers with a request: "Hi, app, show to the user a window with given title, two (or more) lines, some buttons, and send me back the number of line that user selected". The app shows this window and send back to the receiver the user choice. The app has no idea that every line means in this dialog. Due to such a generic form of station menu I do not see any solution to detect, store, and replay necessary settings. However, I leave the issue open. Maybe later I will found a way to solve it...

**Comment by mkulesh** [comment]
Unfortunately, there is no technical possibility to implement it.
