### ISSUE TITLE
TX-8390: Net-Services Deezer / TuneIn loosing login credentials

### ISSUE THREAD

**Issue by derHSE** [mkulesh/onpc#143]
Hi, first a big thanks to you for deploying the app via F-Droid. This was one of the reasons to buy an Onkyo AVR (Onkyo should be thankful to you too!)

First, the TX-8390 is not on the supported models list, how to get it there? Collect logs?
Most parts of the app work fine.

Second, when using Onkyo Controller App, using TuneIn, Deezer and Soptify works as expected. When using onpc, the app always asks again for re-entering the login credentials for Deezer and TuneIn. Any idea on this?

Firmware is up to date. When collecting logs, can I use the regular F-Droid App and collect logs via "The second way: using Android Debug Bridge"?

**Comment by mkulesh** [comment]
Hi @derHSE,
thank you for submitting the issue. I have never heard previously about such a problems on other models. The app does not have any special logic for login credentials for Deezer and TuneIn; the app is here a thin client and all this functionality is done on the receiver side. 

Many people reported me that some strange behavior of the receiver like connection lost, unstable work of the network services like Tidal and many other issues can be fixed by factory reset of the receiver. I suggest to perform the factory reset and setup all login credentials with Onkyo Controller App. At the first start after factory reset, the Onkyo Controller App asks to confirm some privacy agreements, I suggest to confirm it since it may have impact on login functionality. 

If this does not help, I suggest to continue with the log analyze. The official build on F-Droid and Google Play has any logging disabled. Could you please install for it the latest nightly build from here: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.12-debug.apk

I only need the log after application start and until the message for re-entering the login credentials appears. If this message appears, please discard it and do not enter any passwords in the app since the receiver and app send these passwords in plain text and it will be stored in the log. Please also do not paste the log here; instead of it just send it me per email.

**Comment by derHSE** [comment]
Hi @mkulesh, thanks for your reply. As suggested from you:

1) Prechecks
Firmware is up to date (R109-0205-01 10-0028)
Factory Reset

2) Initial Setup
Onkyo Group Privacy Statement: Accept
Chromecast built-in: No

Checked 5-2. Network: Privacy Statement Accepted

3) Onkyo Controller App
NET
TuneIn / Login: Entered credentials / Logged in correctly
Deezer / Hint for Deezer Premium+ / Login: Entered credentials / Logged in correctly

Switched between the 2 services, all ok!

4) Musik Kontrolle / Erweiterte Bedienung für Onkyo und Pioneer (onpc) app
Receiver was found at once
Switched to Media (Medien), plays TuneIn (as left from Onkyo Controller App), is logged in

Go to Media / Deezer / Hint for Deezer Premium+ (again) / Onkyo Group Privacy Statement: Accept (Again)
Login credentials are cleared and have to be re-entered

Go to Media / TuneIn Radio: Login credentials are cleared and have to be re-entered

Maybe there are issues comming from the Privacy Statement that seems to be resetted when using onpc.
I will try to take some logs and send it to you.

**Comment by derHSE** [comment]
Hello Mikhail

Attached the logfile. Did the same procedure as described on Github.

Hope, that you can see anything inside (I am only a systems admin at our
university, not familiar with programming).

Best regards
Guido

Am 18.04.20 um 15:33 schrieb Mikhail Kulesh:

**Comment by mkulesh** [comment]
Hi @derHSE,
thank you for logging. I see some strange behavior with Onkyo privacy policy. I have an experimental version that does not change any privacy policy state. Could you please try it:
 https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v2.3-release.apk

**Comment by derHSE** [comment]
OK, did what you suggested:

1. Prechecks
- Checked Onkyo Group Privacy Statement as Accepted
- With Onkyo Controller App logged in to Deezer / TuneIn, switched between, all ok!

2. Android 9 LineageOS (without GAPPS) / onpc 2.3.0
- Switched to Media (Medien), plays TuneIn (as left from Onkyo Controller App), is logged in
- Switched to Deezer, is logged in
- Switched back to TuneIn, is logged in.

This App seems to work as expected. So, this result gives me hope, that the issue can be fixed. What do you think?

**Comment by mkulesh** [comment]
Released in version 1.12
