### ISSUE TITLE
Memorize multiple devices

### ISSUE THREAD

**Issue by dlandr** [mkulesh/onpc#144]
A proposal : memorize 2 or more IP address/port for switching between devices in the software.

**Comment by mkulesh** [comment]
Hi @dlandr, this feature is now implemented and works as follows:
- In the connection dialog, a new check box "Save connection" and a linked edit field is added. If the given connection can be established (address and port are valid), the given pair address/port will be saved within the app configuration with given name. It is not possible to save more than one device with the same IP/port pair. However, you can save IP/port (like 192.168.1.50/60128) with one name and HOST/port (like onkyo/60128) with other name even these two addresses correspond to the same physical device:
![connect_dialog](https://user-images.githubusercontent.com/30557348/81230192-4eca6a00-8ff1-11ea-9e0c-b38388dcd4b4.png)

- all stored connections are shown in the app navigation drawer together with the devices found in the local network. If no WiFi is available, stored devices are sown, but no auto-discovered devices. If the IP address of a stored device is found in the local network, both items are shown (i.e. you have two items for the same physical device with different names). Furthermore, if the app is currently connected to such a device, both items are selected:
![navigation_drawer](https://user-images.githubusercontent.com/30557348/81230752-56d6d980-8ff2-11ea-9f00-25cb4e7d370b.png)

- If you press on the pencil icon in the right of the stored device name, the "Edit connection" dialog appears. Here, you can change the name or delete this item. The change of address and port is here not possible. If you need to change it, delete this connection and reconnect the target device using "Connect" dialog:
![edit_connection](https://user-images.githubusercontent.com/30557348/81230981-bdf48e00-8ff2-11ea-9cbc-5f7d625ec1d2.png)

Could you please install the latest nightly build from here
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.13-debug.apk
and test how does it work for you?

**Comment by dlandr** [comment]
Hello Mikhail,

I tryed to install the apk :

Settings -> Apps & notifications -> Advanced -> Special app access -> Install unknown apps -> Files -> authorize

But I have a message : "Application non installée" (not installed) when I install from Google Files.

When I launch your application, I still have V1.12.

The Android version is 10.

What do I do wrong ?

Regards,

Denis

________________________________
De : Mikhail Kulesh <notifications@github.com>
Envoyé : mercredi 6 mai 2020 23:41
À : mkulesh/onpc <onpc@noreply.github.com>
Cc : dlandr <dlandr@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mkulesh/onpc] Memorize multiple devices (#144)


Hi @dlandr<https://github.com/dlandr>, this feature is now implemented and works as follows:

  *   In the connection dialog, a new check box "Save connection" and a linked edit field is added. If the given connection can be established (address and port are valid), the given pair address/port will be saved within the app configuration with given name. It is not possible to save more than one device with the same IP/port pair. However, you can save IP/port (like 192.168.1.50/60128) with one name and HOST/port (like onkyo/60128) with other name even these two addresses correspond to the same physical device:
[connect_dialog]<https://user-images.githubusercontent.com/30557348/81230192-4eca6a00-8ff1-11ea-9e0c-b38388dcd4b4.png>

  *   all stored connections are shown in the app navigation drawer together with the devices found in the local network. If no WiFi is available, stored devices are sown, but no auto-discovered devices. If the IP address of a stored device is found in the local network, both items are shown (i.e. you have two items for the same physical device with different names). Furthermore, if the app is currently connected to such a device, both items are selected:
[navigation_drawer]<https://user-images.githubusercontent.com/30557348/81230752-56d6d980-8ff2-11ea-9f00-25cb4e7d370b.png>

  *   If you press on the pencil icon in the right of the stored device name, the "Edit connection" dialog appears. Here, you can change the name or delete this item. The change of address and port is here not possible. If you need to change it, delete this connection and reconnect the target device using "Connect" dialog:
[edit_connection]<https://user-images.githubusercontent.com/30557348/81230981-bdf48e00-8ff2-11ea-9cbc-5f7d625ec1d2.png>

Could you please install the latest nightly build from here
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.13-debug.apk
and test how does it work for you?

**Comment by mkulesh** [comment]
Hi @dlandr,
it can happen since the debug version is not signed and Android blocks sometime to install an unsigned version.
I build today the signed version as well: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.13-release.apk
If Android will have a problem to install this APK, please remove the previously installed version before installation of this file.

**Comment by dlandr** [comment]
Hi Mikhail,

This time I could install the version after uninstalling previous production version.

I tested it and I saw that with wifi and local ip adresses/ports it runs fine.

But when I use public IP adress of box and ports,  only the last one stay memorized and not in the new list.

So, for me it's the same as before 😏

Have a good evening and week-end !

Denis


________________________________
De : Mikhail Kulesh <notifications@github.com>
Envoyé : jeudi 7 mai 2020 22:19
À : mkulesh/onpc <onpc@noreply.github.com>
Cc : dlandr <dlandr@hotmail.fr>; Mention <mention@noreply.github.com>
Objet : Re: [mkulesh/onpc] Memorize multiple devices (#144)


Hi @dlandr<https://github.com/dlandr>,
it can happen since the debug version is not signed and Android blocks sometime to install an unsigned version.
I build today the signed version as well: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.13-release.apk
If Android will have a problem to install this APK, please remove the previously installed version before installation of this file.

**Comment by mkulesh** [comment]
Hi @dlandr,

**Comment by mkulesh** [comment]
Hi @dlandr,
difficult to say why it happens... From code point of view, there is no difference between WiFi and non-WiFi mode. Please note that a connection will be only saved if device was connected successfully. In case of any connection error, the target device will not be added.

Did you have any messages about failed connection in non-WiFi mode? If not, it seems to de a bug that I currently not understand. Could you please collect end send me application logging as follows:
- Disable WiFi in order use public IP address of box
- Remove all stored devices from navigation drawer
- Open application settings and activate "Developer mode"
- Close the app
- Open app again
- Open Connect dialog and connect to the first device using public IP address, save this address
- Observe whether there are any connection errors
- Open Connect dialog again and connect to the second device using public IP address, save this address
- Observe whether there are any connection errors
- Open navigation drawer and take a screenshot
- Open Main menu (three dots on right-top of the app), select latest logging, select whole text and send it me per email with token screenshot of the navigation drawer on mikhail.kulesh@gmail.com
Please do not attach the log here since it may be huge.

**Comment by mkulesh** [comment]
Released in iOS version 2.4
