### ISSUE TITLE
Short Cut in Media for Music Server (DLNA) 

### ISSUE THREAD

**Issue by jnkn** [mkulesh/onpc#165]

**Comment by jnkn** [comment]
Using DLNA on my server I have to navigate everytime within a serverstructure servername\music\directory\ before directy with the music files starts, e.g. 01-Classical, 02-Soundtrack, 03-RockPop and so on. It would be helpful if a shortcut or a starting point can be created that browsing starts for DLNA at servername\music\directory.

**Comment by mkulesh** [comment]
Hi @jnkn,
unfortunately it is not easy. The app is just a thin client that uses Onkyo ISCP protocol in order to control the receiver. This protocol has no possibilities to save any shortcuts and and than follow it. 
I am now working on https://github.com/mkulesh/onpc/issues/155. This issue shall allow me to write and perform a script containing a sequence of ISCP command that theoretically allows us to go to the any place in the media list tree including DLNA server. However, I have difficulties with it since some receivers does not process some commands like "change to DLNA" correctly and currently I have no solution for it. I still working on this mechanism but can not currently say when it will work. If you have any Android experience and can help me, please write on mikhail.kulesh@gmail.com.

**Comment by mkulesh** [comment]
Will be implemented within #166

**Comment by mkulesh** [comment]
Released in v1.15

**Comment by mkulesh** [comment]
Released in iOS version 2.6.3
