### ISSUE TITLE
Rename "Shortcut" tab to "Favourite"

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#175]
- I'm wondering it the name "Shortcut" is the right one. It also could be "Bookmark" or "Favourite".
- "Favourite" was also one suggestion I had. "Bookmark" does not match because we are talking about something you hear and not read. I am still searching for a better name but I think that "Favorite" could be the solution.

**Comment by qpkorr** [comment]
For what it's worth, I kind of prefer Shortcut:
- it's shorter
- it accurately describes what it is - a faster (or less effort) method to reach an item
- it may be that it's linking to something you don't actually like much, but wish to save a quick link to - so Favourite might be a misnomer
- I agree that there's no reason to bring concepts from a book into an audio app - though at least Bookmark doesn't add potentially unintended meaning like Favourite might

Maybe Bookmark and Favourite are more widely used in similar apps - though I see some value in not using those terms since unlike most Bookmark/Favourite applications which jump straight to the destination, onpc is forced to step through the intermediate steps. (I guess this could be hidden from the user, but given they need to wait for it to happen, and it could fail (if, say, DLNA files have changed), displaying intermediate progress seems optimal to me).  

Shortcut is not without precedent - Windows has always used the term for creating a quick way to reach an item (a file path).

That said - I suppose this is bikeshedding - and I care about the functionality 1000 times more than the name so call it what you want :)

**Comment by mkulesh** [comment]
Hi @mastermichi,
Based on the comment from @qpkorr above, I suggest to use "Favourite" in German translation only and keep "Shortcut" in the base English translation. How do you think? If you agree with it, could you please adapt the German translation?

**Comment by mkulesh** [comment]
Released in iOS version 2.6.3

**Comment by mkulesh** [comment]
Released in version 1.17
