### ISSUE TITLE
Alarm clock/Timer for internet radio

### ISSUE THREAD

**Issue by medikoo** [mkulesh/onpc#185]
Tuner on it's own provides an Alarm feature but only for FM/DAB radio or plugged in CD.

It'll be great to have capability to wake up to chosen internet radio station. I imagine that app on its own could at scheduled times turn on the tuner and set specified program.

Have such feature been considered?

**Comment by mkulesh** [comment]
Hi @medikoo,
I do not plan to integrate such features since there are other cool apps that have much more functionality related to scheduled tasks. The app has already support for "Tasker" app, see https://github.com/mkulesh/onpc/issues/184.
I suggest to install Tasker and configure a special script in the Tasker that will start my app based on your scedule, pass this script to the app and the app will than perform this script. The script can set the specified program that you need. Please see https://github.com/mkulesh/onpc/blob/master/doc/Tasker/README.md for more details. Please install Tasker and write me on mikhail.kulesh@gmail.com. I will provide you a script that start, for example, a TuneIn station.

**Comment by medikoo** [comment]
Thanks @mkulesh for all the info. That's very helpful, I'll try the Tasker
