### ISSUE TITLE
Expand message script by new commands

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#186]
There are some possible expansions of the message script:
- Add a new command that starts a shortcut stored in the app
```
<shortcut name="ABC"> 
```
- When searched for something and no items were found, then the NTC PAUSE message returned nothing, with no items to play. We need to expand message script handler by the following check: if outgoing command is NTC PAUSE, playback state is paused, and no media entries are available, just report that the desired state is reached and skip the command. 
- I wonder if it might be possible for onpc to broadcast an intent with the number of results found. Could be a useful interaction - eg "search for x" "5 results for x found" "play the first of them", vs "search for y" "0 results for y found" "ok, I'll go search youtube instead...". We may add following command:
```
<intent target="Tasker", template="found %s titles", content="items_number">
```
- often is necessary to check a state (fr, example, power state or input channel) and change it if it has different value. We use two command for it:
```
  <send cmd="SLI" par="QSTN" wait="SLI"/>
  <send cmd="SLI" par="24" wait="SLI" resp="24"/>
```
Propose to replace it by one new tag like
```
<set cmd="SLI" par="24"/>
```
that performs in background both commands listed above.

**Comment by mkulesh** [comment]
Hi @qpkorr
that do you think about proposed "set" tag?

**Comment by qpkorr** [comment]
Hi @mkulesh,
I'm not sure.
I fully agree with your intent - I'm just inclined to think that it should be implemented with the existing 'send' command, rather than adding an extra command.  The onpcScript send command obviously isn't directly equivalent to an ISCP message send, because the onpcScript send command promises to wait until the appropriate response message is received, guaranteeing that the sent state has become active.  If the ISCP protocol (or rather the receiver that implements it) is, effectively, inconsistent whether it provides that response or doesn't, then it feels like it's onpc's responsibility to honour it's 'promise' to users of onpcScript.  
The only reason not to roll this functionality into the existing 'send' command that I can think of is because it would be hiding things, non-transparent compared to the ISCP messages - but as I say, onpcScript is not the same as ISCP even though it's largely sending ISCP message - it's better ;)
Oh - there's also some messages that don't support QSTN right - was it NTC(PAUSE)? It'd be nice to have a command to say "put the receiver into playing state" - and know it is done if at all possible, regardless of the state it was in.
Anyway - you're the ISCP expert - you probably have ten reasons why 'set' is the right answer, not 'send' - I'm ready to be enlightened :)

**Comment by mkulesh** [comment]
Hi @qpkorr,
I think there is no more need to expand the message script. From my point of view it now works stable and covers all use cases that we need. If you agree, I would like to close this issue.
