### ISSUE TITLE
Album covers from Spotify or radio logo from TuneIn are not visible

### ISSUE THREAD

**Issue by Pivek** [mkulesh/onpc#195]
In official Onkyo application they are visible, however, in "	
Enhanced Controller for Onkyo and Pioneer" they are not.
I am using Onkyo TX-8390

**Comment by mkulesh** [comment]
Hi @Pivek,
thank you for problem report. I tested the app on several devices and have never observed such a problem. It seems to be a device-specific bug. In order to fix it, I need the application log. Could you please collect it and send me per email as follows:
- Download and install the latest nightly build: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.20-debug.apk
- Note that this debug version is not signed. You may need to remove the signed version, installed from Google Play or F-Droid before installing this debug version.
- Open "Settings" dialog and activate the "Developer options" at the end of the settings list
- Go back to the App. An application menu (three dots on the right of toolbar) appears
- In the app, start playing a song from TuneIn
- After the song is started playing and you expect to see an album cover, press the application menu button and select the menu "Latest logging"
- Long press on the text and press "Select All" from the context menu
- Copy this text in the buffer ("Copy" from the context menu) and send it me per e-mail to mikhail.kulesh@gmail.com
- Please also attach a screenshot of the LISTEN tab where album cover is missing
- Open "Settings" dialog again and DISABLE the "Developer options"

**Comment by mkulesh** [comment]
No response
