### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [mkulesh/onpc#2]
Hi, I'm a logo designer, I saw your project and I can make a free logo for your project. So, what do you think?

**Comment by mkulesh** [comment]
Hi @tebriz159, thank you! I will be really happy if you help me with logo improvements. I have no experience in design and, therefore, any help in this area is useful for me. Do you know the technical requirement for Android launcher icon or shall I provide this information to you?

**Comment by tebriz159** [comment]
@mkulesh I'll help you with logo. Can you give me information about logo? which colors do you prefer and what name do you want to use for logotype?

**Comment by mkulesh** [comment]
@tebriz159 I prefer green (Teal) or blue (Indigo) colors. For any Android app, there are following images necessary:
- A logo 1024 x 500 (PNG) also used in Google Play as an app headed (https://github.com/mkulesh/onpc/blob/master/images/app_header.png)
- An application (launcher) logo in two versions: the first one with round shape and transparent background for latest Android versions and the second one with the square shape that in used in older Android versions (see https://github.com/mkulesh/onpc/tree/master/images/launcher). Here I need two SVG files since the icon itself shall be generated for different sizes (different resolutions)  
-  A logo 512 x 512 (PNG) used in Google Play (https://github.com/mkulesh/onpc/blob/master/images/icon512.png) that can be generated from launcher SVG file with square shape

I have no idea about the name. In any case, the word ONKYO shall not be used from copyright reason. Usually all images listed above does not contain any text.

**Comment by tebriz159** [comment]
Okay, I will start to design.

**Comment by tebriz159** [comment]
Hi again, I made a design. I made different color variations and used the colors that you wanted. If you like the design, which color variation do you want?
![omcpre](https://user-images.githubusercontent.com/31902754/51089933-7ffe9700-1729-11e9-8645-6839d0b9245b.png)

**Comment by mkulesh** [comment]
Hi @tebriz159, it looks great! Fantastic! I like blue color:
![screenshot from 2019-01-13 21-54-19](https://user-images.githubusercontent.com/30557348/51090567-d4336680-177d-11e9-957d-eae14fe107e3.png)
Do you prefer to submit a pull request? If yes, could you please submit two SVG files:
- Adaptive icon for the latest Android (square shape): https://github.com/mkulesh/onpc/blob/master/images/launcher/ic_launcher_adapt.svg
- Standard icon for the older Android versions (round shape): https://github.com/mkulesh/onpc/blob/master/images/launcher/ic_launcher.svg
I will than generate all PNGs and bild new version. Alternatively, just attach SVG here.

**Comment by tebriz159** [comment]
I uploaded all files to google drive. 512 px, monochrome and the other versions is here: https://drive.google.com/open?id=1Lb25-opid8iwLrdY2dGdwJ-I3d3eTne1

**Comment by mkulesh** [comment]
Hi @tebriz159, thank you, I was able to import your SVG into the app. From my point of view the width of lines is too small and the inner drawing looks too thin on the real device in comparison to other apps, see two screenshot obtained for two different devices:
![device-2019-01-14-225710](https://user-images.githubusercontent.com/30557348/51144119-80de1880-1850-11e9-9945-4ca751d5dedc.png)
![screenshot_20190110-232010](https://user-images.githubusercontent.com/30557348/51144120-80de1880-1850-11e9-9e48-f66de7f7bfc1.png)
Is it possible to increase the line width approximately by 50% (or maybe, 100%)?

I committed the launcher icon and prepared an APK with new icon:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.5.apk

Could you please test the icon on your device by installing this apk? That do you think about the lines width? 

I would like to add you name into the author list on github project page and into the "About" dialog of the app. If you agree, could you please provide me you name and E-mail?

**Comment by tebriz159** [comment]
I will do it but now I'm sick. I will do it when I heal

**Comment by tebriz159** [comment]
I'm sorry man, I was sick that's why I couldn't make it. But now it's ready, you can download the files from here: https://drive.google.com/open?id=1UbfYs28G4xMXHOSOCCcy92V3p7NE5y_d

**Comment by mkulesh** [comment]
Hi @tebriz159, thanks! Now it looks much better:
![screenshot_20190117-224048](https://user-images.githubusercontent.com/30557348/51350638-fba17080-1aa8-11e9-8586-0b90cf8db7ee.png)
I downloaded and stored your last collection. I think I can close the issue. 

You can any time add your name into the "Copyright" section on the bottom of the main project page. To do it, just create a pull request for the file https://github.com/mkulesh/onpc/blob/master/README.md

**Comment by mkulesh** [comment]
Fixed in release v0.6

**Comment by tebriz159** [comment]
Looks great on google play )

**Comment by tebriz159** [comment]
By the way, I've posted this contribution on utopian (steemit) https://steemit.com/utopian-io/@tebriz/logo-design-for-open-music-controller
If you need a logo design for any project please let me know.

**Comment by mkulesh** [comment]
Thank you, I added the link to your post on utopian into the publication list on the main project page. 
At the moment, I see a lot of possible improvements for the app where a professional designer like you can help.

For example:
- I use some images (see https://github.com/mkulesh/onpc/tree/master/app/src/main/res/drawable-nodpi) for empty album cover, amplifier an CD player. They could be replaced by styled vector drawings.
- Currently, I use FOSS common icon from http://materialdesignicons.com. It is also possible to replace them by some styled icon set.
- Currently,  I have 6 different color themes. A review of these themes and development of some new themes would be nice.
- Due to high density of visual elements on the playback tab I have problem with screen layout in landscape mode. It is also an area where a review of current design will be really helpful for me.

If these points are inline with your interests I would be really happy to receive any ideas and suggestions from you :)
