### ISSUE TITLE
Remote control of Android devices possible?

### ISSUE THREAD

**Issue by r4dh4l** [mkulesh/onpc#206]
Hi,

yesterday I found "Enhanced Controller for Onkyo and Pioneer " on [F-Droid](https://f-droid.org/packages/com.mkulesh.onpc/) and wanted to ask: Is there a possibility to control other Android devices with the App?

My use case: I have a Pioneer [XDP-100R](https://www.pioneerelectronics.com/StaticFiles/PUSA/Files/CEDIA/XDP-100R_Single_Sheet_Final.pdf) DAP (running Android 5) which I use as "streamer" for my stationary hifi setup which can be connected to the DAP via USB.

My current way is to install [Kodi Media center](https://f-droid.org/en/packages/org.xbmc.kodi/) on the DAP and remote control it with [Kore](https://f-droid.org/en/packages/org.xbmc.kore/) installed on my Smartphone. It works but I think it would be more adequate to use your app for my use case. So is there a way to connect Android devices?

**Comment by mkulesh** [comment]
Hi @r4dh4l 
sorry far a late response. The App uses so called "Integrated Serial Communication Protocol" (ISCP) developed by Onkyo in order to communicate with the receiver. This is a client-server protocol, please look at the API description here:  https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_140.xlsx

The App is a client and, therefore, I only implemented a client part of this protocol. My App expects that the controlled device implements the server part. If you wish to control an Android device using my app, there shall run a service that works as a ISCP server and implements the server part of the protocol. Is I know there are no such servers. 

I have no experience with Kodi. As I see this is an open source app. It means it is possible to expand it by ISCP server (that shall be implemented within Kodi). However it may be tricky since Kodi is written in C++. Please ask the developers of Kodi whether it is possible or not.

**Comment by r4dh4l** [comment]
Thx @mkulesh for your detailed explanation!

> The App is a client and, therefore, I only implemented a client part of this protocol. My App expects that the controlled device implements the server part. If you wish to control an Android device using my app, there shall run a service that works as a ISCP server and implements the server part of the protocol. Is I know there are no such servers.

I understand.

> I have no experience with Kodi. As I see this is an open source app. It means it is possible to expand it by ISCP server (that shall be implemented within Kodi). However it may be tricky since Kodi is written in C++. Please ask the developers of Kodi whether it is possible or not.

Okay, and maybe this is out of scope of the Kodi project. SInce I can run Kodi on the player I want to control and the Kodi remote control app "Kore" does a similar job as your app I think I'm fine using Kodi+Kore. Thank you anyway!
