### ISSUE TITLE
Add Zone3

### ISSUE THREAD

**Issue by hopeeuk** [mkulesh/onpc#218]
Could the ability to control zone3 please be added

**Comment by mkulesh** [comment]
Hi @hopeeuk,
thank you for submitting an issue. Actually, the app already supports Zone3. In case if Zone3 is not working for you it may be a receiver-dependent problem. In order to solve it, please provide me some more information.
1. Which app version do you use
2. Which receiver model do you have
3. Please download and install the latest build from here: https://github.com/mkulesh/onpc/raw/autobuild/release/MusicControl-v2.10.0-android.apk
4. If you use iOS, please install the latest version from TestFlight https://testflight.apple.com/join/oV5j2iMh
5. Alternative you may install the desktop version of the app. Actual builds for macOS/Windows/Linux are available here: https://github.com/mkulesh/onpc/tree/autobuild/release
6. After it, please do following:
- Open application settings and activate the “Developer options”
- Close the app and open it again
- In the application menu, select Zone3
- Power on you receiver from the app by clicking "Power on" button
- Try to start a playback from any channel
- Decrease and increase the master volume
- From the application menu, select "About" and than "Latest logging"
- Copy whole text from it into clipboard and send me per email on mikhail.kulesh@gmail.com
Note: Please do not attach this log here since github may truncate it!
This information can help me to solve your problem.

**Comment by mkulesh** [comment]
Closed due to missed information
