### ISSUE TITLE
Onkyo ht-r695

### ISSUE THREAD

**Issue by kartun83** [mkulesh/onpc#219]
Incorrect usb name.
This unit does not have front usb, but only rear usb. But in settings it is referred as front usb.

**Comment by mkulesh** [comment]
Hi @kartun83,
In order to solve this probel, please provide me some more information:
1. Which app version do you use?
2. Please download and install the latest build from here: https://github.com/mkulesh/onpc/raw/autobuild/release/MusicControl-v2.10.0-android.apk
3. If you use iOS, please install the latest version from TestFlight https://testflight.apple.com/join/oV5j2iMh
4. Alternative you may install the desktop version of the app. Actual builds for macOS/Windows/Linux are available here: https://github.com/mkulesh/onpc/tree/autobuild/release
5. After it, please do following:
- Open application settings and activate the “Developer options”
- Close the app and open it again
- Take a screenshot from the settings where you observe the front usb
- In the MEDIA tab, select rear USB
- From the application menu, select "About" and than "Latest logging"
- Copy whole text from it into clipboard and send me per email on mikhail.kulesh@gmail.com together with the screensot

Note: Please do not attach this log here since github may truncate it!
This information can help me to solve your problem.
P.S. You can write me per Email in Russian.

**Comment by mkulesh** [comment]
Closed since missed information
