### ISSUE TITLE
3-way toggle for Zone 2 A and B speakers

### ISSUE THREAD

**Issue by onschedule** [mkulesh/onpc#22]
Rather than seperate "on / off" button for both Zone 2A and Zone 2B, perhaps one button that toggles between "Zone 2A + 2B" - "Zone 2A Only" and "Zone 2B Only" (this would prevent the unit from being sent to "Standby" power mode by accident when both zones are turned off at the same time?)

**Comment by mkulesh** [comment]
Hi @onschedule, thanks, good idea. Scheduled for release 0.8. And that about the main zone? Also one three-way switch instead of two separate switches or this zone is usually related to other use case?

**Comment by onschedule** [comment]
I have not familiar with using in this manner- I only use for Zone 2 so my
ideas would be of little use.

**Comment by mkulesh** [comment]
Hi @onschedule, I added three-way switch for both zones (main and Zone 2). 

Could you please test it? Please use the latest nightly build 
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.8-debug.apk

It is possible that you plugin your speakers to main zone instead of  Zone 2 in order to test this zone as well? Or the main zone does not have corresponding connectors for your speakers?

![device_tab](https://user-images.githubusercontent.com/30557348/53125837-275bbe80-355f-11e9-9606-4558eb75a4ee.png)

**Comment by onschedule** [comment]
Wonderful- I look forward to testing it out this weekend!

**Comment by onschedule** [comment]
I left on a business trip before testing. I apologize for the delay. I will
test upon my return...

**Comment by mkulesh** [comment]
Released in version 0.9
