### ISSUE TITLE
Linux build causes constant high CPU load

### ISSUE THREAD

**Issue by quelbs** [mkulesh/onpc#222]
The Linux build from #211 causes a high CPU load whenever it is running.
The CPU load on my quadcore is around 75%, also when the interface is inactive (not visible).
The reason might be a permanent repainting, because it is around 60% of the CPU usage comes from MusicControl and 15% CPU for the Xorg deamon.

**Comment by mkulesh** [comment]
Hi @quelbs 
yes, I also have a high CPU load an some distos like CenOS 7. However, on Fedora 30 workstation CPU load is moderate but acceptable:
![cpuLoad](https://user-images.githubusercontent.com/30557348/108622581-14c03c80-743a-11eb-9c7b-84d9268ffdc2.png)
I have 8 cores here and one core has load about 20%. But I also have GeForce GTX 1050 Ti in the system that may decrease the CPU load since Flutter uses GPU when available. 

Currently the are a lot of open issues in Flutter related to the Linux platform: https://github.com/flutter/flutter/issues?page=3&q=linux+is%3Aopen
I will observe these issues and build a new version when performance problem is solved.

**Comment by mkulesh** [comment]
Released in version 2.10.4
