### ISSUE TITLE
Volume slider in Group/Ungroup popup

### ISSUE THREAD

**Issue by reyostallenberg** [mkulesh/onpc#224]
Wouldn't it be nice to somehow have volume control for grouped devices without the need to select the device

So if you group device 2 on device 1 you can manage the volume of device 2 in the part of the app that manages device 1.

I would like to try to work on this if you like, but before I begin I would like to know what your idea is on this functionality

**Comment by mkulesh** [comment]
Hi @reyostallenberg 
I think this a good idea. If you like to implement this feature, I am happy with it and will provide you all information. 
First of all please note that I have two different sources:
- The master brunch https://github.com/mkulesh/onpc contains the native Android code (Java) of the free version
- The second branch https://github.com/mkulesh/onpc/tree/onpc-flutter contains platform-independent premium version written with Dart/Flutter. Currently, this code works not only on Android/iOS, but also on desktop platform (Linux/Windows/macOS). I personally prefer for my development the Flutter code since it is more comfortable for me to develop and debug on the same desktop rather than develop on desktop and debug on attached mobile device. On the other hand, the desktop development needs more tools installed (like Flutter/Dart, VC on Windows, additional libraries on Linux or XCode on mac).

You can select the branch for your development and I can merge the solution into other branch.

Some technical background. The app implements so called ISCP protocol in order to communicate with the receiver. The protocol is described here: https://github.com/mkulesh/onpc/blob/master/doc/ISCP_AVR_140.xlsx

With respect to protocol, my app has some parts:
- The first part is the protocol implementation (network monitoring, message channel, messages, application state, state manager): https://github.com/mkulesh/onpc/tree/onpc-flutter/lib/iscp. It is a "model" part if we talk about MVP pattern. I expect that this part needs no extensions for this feature. The major class here is https://github.com/mkulesh/onpc/blob/onpc-flutter/lib/iscp/state/MultiroomState.dart that holds the list of all discovered devices that can be grouped.
- There is configuration classes used to hold and manipulate app configuration: https://github.com/mkulesh/onpc/tree/onpc-flutter/lib/config. I also expect no changes here.
- There is also a list of common widgets that are used to build GUI: https://github.com/mkulesh/onpc/tree/onpc-flutter/lib/widgets. Also no need to expand it.
- And the important part is the GUI implementation that contains a lot of views: https://github.com/mkulesh/onpc/tree/onpc-flutter/lib/views. These views subscribe on different update events and implement the "view and presenter" logic. The view to be expanded for this feature is https://github.com/mkulesh/onpc/blob/onpc-flutter/lib/views/GroupControlView.dart that implements the "Group/Ungroup" dialog. The simplest first solution may be to expand this dialog: either add a volume slider to each device that belongs to a group or add buttons "+" and "-" that synchronously sends the Up/Down commands to all grouped devices. 

Of course there are a lot of other solutions like re-define master volume control if a group is active, add a new dialog like "Group volume control", add new buttons to the existing master volume control view or master volume dialog, etc. Do you have any ideas about possible GUI implementation for this feature?

**Comment by mkulesh** [comment]
No response
