### ISSUE TITLE
Manual IP address entry UI enhancement request

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#23]
After entering a IP address manually, a connection attempt isn't made until the network icon is tapped.  This wasn't obvious to me.  I had assumed that once I hit enter, it would try to connect.  I think both options should be supported (icon and/or enter).

**Comment by mrlad** [comment]
BTW, I do think @onschedule is right, you need to highlight VPN functionality.  I *think* this is the only remote control app that allows you to enter an IP address an not rely on a broadcast.

**Comment by mkulesh** [comment]
Hi @mrlad, please update the app. I moved connection menu from DEVICE tab into navigation drawer. If you selects this menu, a connection dialog appears where you should enter address and press OK for connection. With respect to this change I think this issue is already deprecated, here is nothing to do :)

![navigation_drawer](https://user-images.githubusercontent.com/30557348/52883501-77a3dc80-316b-11e9-82a3-8b4683efcd7b.png)

![device_connect](https://user-images.githubusercontent.com/30557348/52883530-9904c880-316b-11e9-9a55-1d58ac57450b.png)

**Comment by mrlad** [comment]
@mkulesh you are correct. This is already fixed!  Please close.

**Comment by mkulesh** [comment]
No problem anymore
