### ISSUE TITLE
Possible to add manual URL for streaming radiostation not in TuneIn Radio

### ISSUE THREAD

**Issue by 5a54a** [mkulesh/onpc#231]
Would it be possible to manual add an URL for streaming radiostation (which is not in TuneIn Radio)?

**Comment by mkulesh** [comment]
Hi, thank you for request and sorry for a late response. I am not sure about streaming radiostation (which is not in TuneIn Radio) since I have no such a stations in my Onkyo device. In order to add it I need you help. Could you please attach a screenshot with such a station and collect the app log as follows:
- Download and install the latest nightly build, for example https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.23-debug.apk. Note This debug version is not signed. You may need to remove the signed version, installed from Google Play or F-Droid before installing this debug version.
- Open "Settings" dialog and activate the "Developer options" at the end of the settings list
- Go back to the App. An application menu (three dots on the right of toolbar) appears
- In the APP, go to the top of the NET services
- Select and start playing of your streaming radiostation
- Take screenshot
- Press the application menu button and select the menu "Latest logging"
- Long press on the text and than press "Select All" from context menu
- Copy this text in buffer ("Copy" from the context menu) and send it per e-mail to mikhail.kulesh@gmail.com (with attached screenshot)
- Open "Settings" dialog again and DISABLE the "Developer options"

**Comment by quelbs** [comment]
As far as I see (at least for my Device), the URL for radio stations can only be added using an http POST request to the receiver with the form available at http://192.168.178.23/station.cgi
I do not know / did not test with submitting parts of the form, but the request looks like this:
```
save=SAVE&name00=Name+Of+A+TuneIn+Station&url00=&name01=Name+for+a+streaming+URL&url04=http%3A%2F%2F...%2Fstream.mp3&...&name39=something&url39=
```
Maybe this helps?

**Comment by mkulesh** [comment]
Hi @quelbs,
thank you for information. On my NS-6170, I have no such a link (http://192.168.178.23/station.cgi). It seems to be this feature is  not really standard and is not available on all Onkyo devices. At the moment I see no possibility to implement this feature.

**Comment by quelbs** [comment]
One additional remark on this: If you have already entered a manual URL and initialize renaming the station (using the menu key on the remote), there is a dialog asking for the station name, followed by a dialog asking for the uri.

![Enter station URL dialog](https://user-images.githubusercontent.com/570222/114031838-0c05b780-987c-11eb-9b44-c738b3c4cd96.png)

But you do not have the device menu available in the app, the app only shows one "Create favorite" ("Favorit erstellen") entry for adding the entry to the app favorites (which is a bit confusing, when you are in the "My favorites" section of the receiver).

**Comment by 5a54a** [comment]
Was unable to respond last weeks, but still very much interested in a solution for this feature request.

I followed your first 4 steps, but do not understand:
> Select and start playing of your streaming radiostation

Do you mean that I should play any random station from TuneIn? Because I do not see any option to manual add a URL for streaming radiostation.
