### ISSUE TITLE
Play Queue Sort Order

### ISSUE THREAD

**Issue by r0bis** [mkulesh/onpc#240]
This is an excellent app. One thing puzzles - when I add DLNA server album to the play queue the order seems a bit random - normally songs are sorted by track number, not here. Secondly - there is no possibility to sort queue. I understand that this may be deliberate; the only sensible way perhaps would be to sort by album, then track order. But this still caused problems - I added 2 albums to the queue and a couple of songs as well, but since the albums were not added with songs normally sorted, this was a problem. Is this a bug, or could this be something that the app could be improved with?

**Comment by mkulesh** [comment]
Hi @r0bis,
thank you for the observations. The insertion into the queue is completely done by the receiver firmware. There are no public interface within the Onkyo network protocol that allows us to advise the receiver how the queue shall be sorted. Therefore that random sorting can not be fixed. 
As a workaround the app allows to resort queue manually. To do it, please try following:
- in the premium version: open the queue, press on the "=" symbol in right of the track and drag and drop the track:
![Screenshot from 2021-11-03 22-06-44](https://user-images.githubusercontent.com/30557348/140192987-2dd1bda4-c78a-4acd-80fa-8d83d807ba24.png)
- in the free version: open the queue, long press on the track to be moved, the context menu appears. Select "Move from". After it, select the track after which the selected track shall be moved. Long press on it. In the context menu select "Move to". The track shall be re-ordered.

Any more automatic re-ordering is unfortunately not possible since the receiver does not provide any tags for the queue items. The app only knows the track title, other information like track number, album or interpret is missing in the Onkyo network protocol. I am also not happy with these limitations of the Onkyo protocol and do not see any ways to improve the sorting in the queue.

**Comment by r0bis** [comment]
@mkulesh Many thanks for telling this, very good to know. It means that if used with the mini-dlna server (which is very convenient with OMV) you only make short queues as they can be sorted manually. If longer playlists are needed one can make M3U playlists and put them on the DLNA server - they can be used then (one just needs to be careful about relative paths). I will reinstall the paid version - this is a very good app. Best wishes!

**Comment by mkulesh** [comment]
Hi @r0bis,
thank you for the hint about M3U playlists on the DLNA server! 
I close the issue since there are no possibility to improve the queue sort due to Onkyo firmware limitations.

**Comment by r0bis** [comment]
@mkulesh One thing that I noticed with the original/official android app - it seems to me that they are much quicker in displaying album art in the app. The picture is there and then after a little while audio starts playing. In your app it seems it might be the other way round - the picture has the spinning hourglass for quite a while (which leaves the impression that _something_ is not working :). This is purely psychological, I guess, but if your app would be able to display the album art in the first instance - quicker before anything else, that would be great.

**Comment by mkulesh** [comment]
Hi @r0bis 
sorry for a late response. Based on your observation, I created a new issue: https://github.com/mkulesh/onpc/issues/253
