### ISSUE TITLE
Allow sorting of network services

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#25]
I'd like the option of being able to sort my network services so they are displayed in the order of my most frequent usage.

**Comment by mkulesh** [comment]
Hi @mrlad, ohh, it was a lot of code changes since I shall completely rewrite setting in order to allow sortable lists. Now, three settings can be sorted: "Input selectors", "Listening modes", and "Network services". I also moved "Friendly selector name" option to the main settings screen since it is not more technically compatible with sorted list screen. The format is saved settings is also changed; it means your previously saved filters for these tree lists is lost in the app and you shall configure it again. Could you please deep retests the use of "Input selectors" (zone-dependent), "Listening modes", and "Network services"?

![sorted_list](https://user-images.githubusercontent.com/30557348/53051173-793b1080-349b-11e9-8211-13c68b732e59.png)

**Comment by mrlad** [comment]
Sorting works great for me!  Very nice.  Thank you.

**Comment by mkulesh** [comment]
Released in v0.8
