### ISSUE TITLE
Add possibility to define global shortcuts for volume control

### ISSUE THREAD

**Issue by parano666** [mkulesh/onpc#252]
First, sorry if I'm not allowed to suggest a feature!

Second, thanks a lot! Best windows avr app!

Request if ever: global windows shortcut to control sound in windows.

Thanks in any case!

**Comment by mkulesh** [comment]
Hi @parano666,
thank you for the idea. Android version has currently a setting "Volume keys turning" that allows to use volume keys on the phone to change master volume on the AVR. That do you mean with "global windows shortcut to control sound in windows"? Do you mean when app is running, the standard windows volume control can be used to change AVR volume like in the Android version? Or something else?

**Comment by parano666** [comment]
Sorry, my not so perfect English. What i meant is; on windows 10 or 11, as my main usage is with the windows app, as i use a htpc all day, I wish I could control the sound of the avr, through your windows app, with a global shortcut (anything. Not necessary the default windows sound control that I stick to 100%. Any global shortcut I could then either assign to a specific key on my keyboard or manually hit by myself (ctrl+alt+ something or whatever make it work).

**Comment by mkulesh** [comment]
hi @parano666,
thank you for details. I will schedule this feature for the next releases. I let you known when the test version will be available.

**Comment by parano666** [comment]
Wow. Thanks a lot in any case!!

**Comment by mkulesh** [comment]
Hi @parano666,
the test build is now available on: https://1drv.ms/u/s!At2sh2-YDyGFenAKTr8MJgMdGLE?e=Ex28fV

This is an MSIX file that shall be installed using Windows App Installer (https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1#activetab=pivot:overviewtab)

However, this MSIX file is signed with so called "Developer certificate" that is not available by default. Without this certificate, App Installer does not allow to install the app.

You shall install this certificate once manually. Please follow this instruction:  https://www.advancedinstaller.com/install-test-certificate-from-msix.html

After the app is installed, a new setting "Global keyboard shortcuts" appears:
![keyboard_shortcuts](https://user-images.githubusercontent.com/30557348/151985049-155a0a19-8fbf-4f00-aab5-c1f20420b4e5.png)

If you select this setting, you will be able to re-define default shortcuts "Alt Num +" and "Alt Num -" for volume control:
![keyboard_shortcuts](https://user-images.githubusercontent.com/30557348/151985423-8f8335ee-2621-43e1-a6a6-82ef8ce11af6.png)

These shortcuts are system-global, i.e also shall work when my app is minimized or not focused. Please try to select shortcuts that are not already assigned to the applications that you usually use. When a shortcut is shared between two or more apps it may not work properly since there are no guaranty that such a key press will be delivered to all apps.

Please test and let me know when you need more shortcuts for other commands.

**Comment by parano666** [comment]
Wow thanks!!! Will try that asap. For other shortcuts, if you want suggestions: in another similar (but buggy app), they mapped locally those keys: Q for quick menu, WASD for navigation (up down left right), F for selecting. Lastly i (I) for info. Really practical for day to day quickmenu changes. 

I think I would probably also like a global shortcut to switch listen mode (dd, all channel stereo, direct.. that list.. would be a next and previous shortcut). 

Thanks again again a lot!
You're making the dream API control avr. Lucky that you're supporting mine (actually using an integra drx 5.3)

**Comment by parano666** [comment]
(for the android app: a persistant notification with volume control would be god send too.)

**Comment by mkulesh** [comment]
Hi @parano666 

> for the android app: a persistent notification with volume control would be god send too
Android app is already able to process hardware volume keys when you activate the setting "Volume keys turning" that allows to use volume keys on the phone to change master volume on the AVR. That do you mean with "persistent notification with volume control"?

**Comment by mkulesh** [comment]
Hi @parano666 
I now expanded the list of global shortcuts. Now the replay control is also available:
![global_shortcuts](https://user-images.githubusercontent.com/30557348/153297994-7588145b-76f4-4c6c-b4a5-bd88bdb85bfc.png)

Could you please install new build from here:
https://1drv.ms/u/s!At2sh2-YDyGFe4nqwEn7-RrAXpw?e=KhzRsd

**Comment by parano666** [comment]
Thanks again alot!
Sorry I've been busy, haven't have the chance to test it all but I'll this weekend.

What I mean about android:
![image](https://user-images.githubusercontent.com/95625778/153403459-18d82e95-15de-468c-8eb7-005bbbb0bbc1.png)

**Comment by parano666** [comment]
You're god send in my day to day use of my windows 11 htcp + avr. The global shortcut are working perfectly (and for those interested, I use power toys in windows 11 to redirect standard global volume control to the global shortcut of the app. Not sure if it works directly into the app, seems better bug proof by using the built in windows 11 remapping).

If you can add the option of local or global shortcut for many other options (input selector, quick menu and navigation, "info" (to display actual video and audio setting), that would be freaking wonderfully perfect!!!

Thanks a lot, bought app for windows and android :)

**Comment by parano666** [comment]
(info is "playback mode" in your app)

**Comment by mkulesh** [comment]
Hi @parano666,

Thank you for testing and feedback!

> That way no need to open the app every time you want to turn up or down the volume: directly accessible in notification (even if phone locked if allowed by global settings) once you have open the app once before.

I have already received a similar request: https://github.com/mkulesh/onpc/issues/114
However, it is not possible to add this feature into the current app. The internal app architecture does not allow to do it in a simple way since the app is currently a "monolith" and does not contain any background services necessary to hold the connection with a receiver. Currently I have no capacity to implement this feature.

> If you can add the option of local or global shortcut for many other options (input selector, quick menu and navigation, "info" (to display actual video and audio setting), that would be freaking wonderfully perfect!!!

My understanding of use cases around global shortcuts is that the shortcuts are used when the app is not visible on the screen (is in the system tray). In this case, you will not see the response of the app on your commands. For me, quick menu and navigation shortcuts are in this case not really helpful. I would prefer to publish new version with shortcuts as it is and collect the feedback from other user before I expand the list of shortcuts.

**Comment by mkulesh** [comment]
Released in version 2.11.1
