### ISSUE TITLE
Internet Radio / Net

### ISSUE THREAD

**Issue by vesty02019** [mkulesh/onpc#263]
When I select "Internet Radio" the app opens "Net" and only allows me to select "Favorites" and no option to see Internet Radio options like Pandora etc.

I have to use the Onkyo app to open Internet Radio options then if I go back to Enhanced Music app I can see and access my Internet Radio options.

**Comment by mkulesh** [comment]
Hi @vesty02019,
thank you for the issue and sorry for a late response. August is a holidays time :)

I believe it is receiver-specific bug since such a problem has been never observed before. In order to fix the problem, I need more technical information about your receiver. Could you please collect and provide me the application log:
- Manually download and install the premium version of the app from here: https://onedrive.live.com/?authkey=%21ANJ7%5FJB5cy7S9tU&id=85210F986F87ACDD%21118&cid=85210F986F87ACDD
- In the application settings, activate "Developer options"
- Close the app and open it again
- Select "Internet Radio" the app
- Keep the app open and start the official Onkyo app on an other device. Open Internet Radio from Onkyo app while "Enhanced Music Controller" still be opened. Close Onkyo app.
- in the "Enhanced Music Controller" go to application menu and select "About". Click on the "Latest logging" tab. Press "Copy to clipboard" button in the right-bottom corner. Paste this log in an emal and send it me to mikhail.kulesh@gmail.com
- Please do not attach this log here in github since it may be huge. 
- In the application settings, disable "Developer options"

I hope this log may help me to debug and fix this bug.

**Comment by vesty02019** [comment]
Hi Mikhail 

I will gladly send you the information requested in about 3 weeks as I am now on holiday. Thank you for getting back to me. 

Sent from my iPhone

John O’Rourke
774-248-4102

**Comment by mkulesh** [comment]
Hi @vesty02019,
is there any updates regarding the log collection for this issue?

**Comment by vesty02019** [comment]
Hi Mikhail

 

Many apologies for the delay… Unfortunately, I’ve been distracted however, I did attempt to download the premium app to install on my Windows Laptop but, I received the below error message regarding certificates.

 

As an FYI, the app that is problematic is installed on my iPhone presently. I believe I understand what you want me to do but, until I can install the app on my Windows v11 / x86-64 I won’t be able to collect the log file you are needing.

 



 

 

 

John O'Rourke

 ***@***.***> ***@***.***

508-876-0089 (h)

774-248-4102 (c)

www.linkedin.com/in/jforourke <http://www.linkedin.com/in/jforourke>

**Comment by mkulesh** [comment]
Hi @vesty02019,
here is important to use two different devices (one for my app and the other one for the official Onkyo app). If you have these two devices, one of which is iOS, my how-to-reproduce written above will work because the iOS version of my app supports all these logging functionality. If the 2nd device is Windows, yes, Windows version of my app is necessary. The windows build is signed using so called developer certificate, it shall be installed in the Windows prior to install my app. Please take a look on this instruction for installing the certificate: https://www.advancedinstaller.com/install-test-certificate-from-msix.html

**Comment by mkulesh** [comment]
The problem is resolved after firmware update, no software changes are necessary.
