### ISSUE TITLE
Firmware-update available, 5 minutes later, the same firmware is actually 

### ISSUE THREAD

**Issue by Joska59** [mkulesh/onpc#294]
![Screenshot_20240124_200759_Enhanced Music Controller](https://github.com/mkulesh/onpc/assets/115286175/9b4b9448-17b5-427c-a0aa-6deacac4280f)

Now I try to update using the Denon app, this has no effect, but 5 minutes later I see.....

Nun versuche ich per Denon App ein Update zu machen, dieses zeigt keine Wirkung, aber 5 Minuten später sehe ich.....
![Screenshot_20240124_201257_Enhanced Music Controller](https://github.com/mkulesh/onpc/assets/115286175/750ad54f-11df-469f-bd88-e764df93f8a9)
Now the same update is suddenly up to date, but every time I use the Heos functionality I am asked to update again, but this is canceled with a download error.
 It's definitely not a bug with the app, but perhaps this phenomenon is known.
The app “makes the mistake” but may receive the wrong information from Heos.

Nun ist das gleiche Update plötzlich aktuell, aber bei jeder Nutzung der Heos-Funktionalität werde ich wieder zum Update aufgefordert, welches aber mit Download-Fehler abgebrochen wird.
Ist bestimmt kein Fehler der App, aber vielleicht ist dieses Phänomen bekannt.
Die App "macht den Fehler mit", bekommt aber möglicherweise die falsche Info von Heos.

**Comment by mkulesh** [comment]
Hi @Joska59,
interesting... We have the same model, but I have actually firmware version 5300-6210-7032-1000 and this version is actual. You can open in browser the page https://192.168.178.197:10443/general/general.html#, select Firmware and check the pending firmware update on the receiver page. As I see on "https://support-eu.denon.com/app/answers/detail/a_id/3832/kw/denon%20dra%20800h", the latest firmware for our model is from 14.12.2023 and I have it installed. It seems to be you have a different version. In order to update, please try following:
- on https://192.168.178.197:10443/general/general.html# ensure that you have a pending update
- if yes, try to update using Denon RC (not the Heos or Denon App!)
- if update failed, perform the factory reset of the receiver and try to update again.

Regarding the indication in my app. I only show the message that receiver send to the app and do not check the version number itself. Garbage in - garbage out. I think it is not possible to fix such an invalid indication in the app.

**Comment by Joska59** [comment]
`Regarding the display in my app. I only show the message the recipient sends to the app and do not check the version number myself. Garbage in - garbage out. I think it is not possible to fix such an invalid ad in the app.` 

As you wrote, I'd had expected, but wasn't. 
The process of firmware-update seems to be a little bit laggy on my receiver, but that is no issue for this thread ;-)

**Comment by mkulesh** [comment]
Hi @Joska59,
yes, I mean Remote Control from the receiver (RC-1235).

**Comment by mkulesh** [comment]
Analyzed, no action needed.
