### ISSUE TITLE
Active Media Sources Not Saved Per Device

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#30]
I've got a 30.7 and a 40.7 on the same network.  I have only 3 sources enabled on the 30.7 and 5 sources on the 40.7.  If I switch from the 30.7 to the 40.7, onpc will only show 3 sources on the 40.7.  It seems like it remembered the number of sources active from the previous device (the labels were correct though, just the number enabled was wrong).

**Comment by mkulesh** [comment]
Hi @mrlad, you are right, the app saved previously the media sources and network services independently from receiver model. I changed this behavior. Now, the selected network services and input selectors (and also their order) are stored with respect to the model of the actually connected device; i.e each receiver model will have own settings. Note: I did not used friendly name here; two receivers with the same model, but different names will share these settings. Please test using this release build: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v0.8-release.apk
Note: this is a signed build (as for Google Play), you may need to uninstall previous version in order to install this build.

**Comment by mrlad** [comment]
Fixed in the release candidate

**Comment by mkulesh** [comment]
Released in v0.8
