### ISSUE TITLE
Support for serial-based Onkyo Receivers via Serial -> Ethernet servers

### ISSUE THREAD

**Issue by ManiacDC** [mkulesh/onpc#311]
I have an Onkyo TX-SR805 which I have hooked up to my network using a Serial to TCP Server (https://www.cdebyte.com/products/NB114). I can send raw ISCP commands over TCP to the receiver to control it (such as !1PWR01 to turn on the receiver).

Would you consider adding support for these older receivers? I haven't had too much time to dig through the code yet, but I would think it would mainly consist of adding another protocol that uses ISCP, but does not add the headers eISCP expects. Would also need a way to configure the IP address and port of the TCP server.

If this is something you'd consider, I could try to work on a pull request/fork for this as I have time. Any pointers to jumpstart me would be great.

**Comment by mkulesh** [comment]
Hi @ManiacDC,
Yes, it is possible. I can provide you a detailed instruction which code shall be changed for it and merge your code into the trunk. However, my app widely uses an XML-extension of the ISCP protocol that is not available on your receiver, i.e almost all controls in the app will be not usable in such a mode. My proposal is to implement this feature in the premium version of the app since this version allows to hide any control element that will be not necessary in your case. Please write me on mikhail.kulesh@gmail.com if you have time for this work.

**Comment by ManiacDC** [comment]
@mkulesh thank you for your response. However, I think I have decided on an alternate implementation. Largely inspired by: https://github.com/cl0rm/eiscp_bridge, I am in the process of writing a tcp relay server that will impersonate an eiscp-capable receiver, strip the eISCP headers, send the raw ISCP command to the receiver, then re-encapsulate the ISCP response as an eISCP response.

In theory, this should allow me to use ANY app that uses eISCP to control my receiver. I'll keep you posted with my progress, I plan to open source it when done.

**Comment by ManiacDC** [comment]
@mkulesh I can confirm pretty much the only functionality your app offers for my receiver is turning it on and off, lol. On the positive side, I have my tcp relay to the point where it's mostly working. Hopefully another few evenings and I'll be ready to share.

**Comment by ManiacDC** [comment]
Done, seems to be working fine. I'll close this issue now. Thanks for being receptive to the idea @mkulesh !
https://github.com/ManiacDC/eiscp-relay
