### ISSUE TITLE
Englarge Mute Button

### ISSUE THREAD

**Issue by nick16** [mkulesh/onpc#314]
Since I only the use mute button within the app (since I use the phone hard buttons for volume control), I would like it be easier for me to mute my receiver.
There's been times where I miss the mute button, and since there's a lot of wasted space on the screen, primarily in the center, I would like to replace the center image with a mute button that fits the entire space, so I can mute my receiver without looking at my phone.

**Comment by mkulesh** [comment]
Hi @nick16,
thank you for a proposal and sorry for a late response since my vacation :)

Unfortunately, a large mute button does not correspond to my design rules. 

Therefore, I implemented a slightly different solution:
- There is now a new app setting: "Album's cover click behaviour":
![Screenshot_20240803_123429](https://github.com/user-attachments/assets/373c42e7-155b-4fae-91d6-7db030eeb147)
- You can now select the value "Audio muting" here: 
![Screenshot_20240803_123556](https://github.com/user-attachments/assets/7de34902-af43-49cb-8101-12e54d1085c1)
- After it, a click on the album cover on the LISTEN tab will have the same effect as the pressing of the mute button:
![Screenshot_20240803_123815](https://github.com/user-attachments/assets/4806e281-63a7-46cc-a20b-c83effe5f64d)

Please find a new test build here: https://1drv.ms/u/s!At2sh2-YDyGFg0JYEkzJw52cQYqZ

**Comment by nick16** [comment]
Just gave your test build a run, and the mute button satisfies my request. I love it! Thanks.

**Comment by mkulesh** [comment]
To be merged into premium version

**Comment by nick16** [comment]
To add onto this idea, what if when the user swipes up on the album cover it increases the volume and swiping down decreases volume. This makes adjusting the volume even easier.

**Comment by mkulesh** [comment]
Hi @nick16 

> To add onto this idea, what if when the user swipes up on the album cover it increases the volume and swiping down decreases volume. This makes adjusting the volume even easier.

Unfortunately it is not possible. I am not able to change the master volume during the scrolling since this operation is slowly on the receiver site. Therefore I send the command after the scrolling is finished and use the progress bar for it in order to indicate the resulting volume before the command is sent. Without such an indication (like in your proposal) there is a possibility to set the master volume to a too high value that may damage the acoustic system...

**Comment by mkulesh** [comment]
Released in version 2.14.0

**Comment by nick16** [comment]
Thats too bad..
To clarify, I was thinking when the user swipes up a single time, it would increase the volume 0.5. Im not proposing a slider, rather a swipe motion to change the volume 0.5 at a time.

**Comment by mkulesh** [comment]
Hi @nick16, if you use Android, you can use the hardware volume buttons to increase/decrease the volume. It is more consistent than the swipe on the album image...
