### ISSUE TITLE
Request: Add the ability to display volume in dB

### ISSUE THREAD

**Issue by tony359** [mkulesh/onpc#317]
Hello there - I was looking for an app to control the volume of my Onkyo from my mobile and found this one which works nicely.

One thing I'd like to see is the ability to change the level displayed by the app to show absolute dB instead of listening level. That is, 0.0dB instead of 82. I set my Onkyo to show absolute dB but the app is not reflecting that.

Unless this is already possible but I had a look into the options and I could not find that.

Thanks for developing this!

**Comment by mkulesh** [comment]
Hi @tony359 

Unfortunately, the receiver provides the information about maximal and current volume as listening level only, this is a constraint of the Onkyo network protocol. I have no information about scaling factor in order to convert this listening level into dB on the app side. Furthermore this factor is model-dependent (and, for some models, also zone-dependent), and I have no possibility to find out such a factor for all supported models.

That is possible - I can introduce three additional setting parameters like min. volume, max. volume and volume step in dB. If you know these parameters for your receiver, you just set all these three parameters and, if these parameters are set, I can scale the listening level and show the volume in dB... Is this solution acceptable for you? Do you know min. volume, max. volume and volume step in dB for each zone on your device?

**Comment by tony359** [comment]
hello
First, thanks for considering my comment.

The levels should be linked by a known amount.

0.0dB is 82dB which is (should be) the reference SPL level of a home theatre.
Then it's all linked. 

-1dB is 81dB
-2dB is 80dB 
(etc)
Also 
+1dB is 83dB etc.

To clarify, the ABSOLUTE level (82, 81 etc) is actually the SPL (sound pressure level) at the listening position. This is assumed of course as very few users will calibrate their system. The other decibel scale is the internal level in dBFS - hence 0.0dB means "the level is what comes from the source, untouched". -1dB is going to be "The input level is lowered by 1dB before it gets to the output" and so on. You'll find the dBFS (Full Scale) level on most professional devices.

When in  dBFS mode I actually have 0.5dB steps (I never tried the absolute mode) so ideally it would be nice to have those as well. But 1dB resolution would be plenty :) 

Does this help?
Thank you a lot!
Tony

**Comment by mkulesh** [comment]
No, it is not really clear for me. I found some models like this:
- TX-L20D:
-- max volume = 30
-- step = 1
- CR-N775
-- max volume = 42
-- step = 1
- TX-NR636
-- max volume = 80
-- step = 1
- VSX-LX302
-- max volume = 82
-- step = **0.5**
- TX-RZ900
-- max volume = 100
-- step = 1 

Could you please provide me the values in dB for min volume (0), max volume (see list above), and, for example, 10 (some level between min and max) for all these models above? Please note that VSX-LX302 has step 0.5 and max volume 82 corresponds to the level 41...

**Comment by tony359** [comment]
My apologies,
I assumed all Onkyo's followed the same logic of my PR-SC5508 which is a pre-amp hence likely designed with "Pro" sound in mind.

The 5508 is simple.

Absolute level 82 corresponds to relative 0.0dB

Absolute level goes from 0 to 98.5
Relative level goes from -82 to +16.5

So for example Absolute 72 corresponds to relative -10dB.

Steps are 0.5.

It feels a lot of work to make this work with all receivers. I thought they all worked the same! I found a list of Onkyo commands online and I see it's VERY limited! what a shame. 

If you feel like trying something, for the 5508 you can just match as below if it's simpler

82 / 0.0
81.5 / -0.5
81 / -1
80.5 / -1.5
80 / -2

etc.

Thanks again!

**Comment by mkulesh** [comment]
Hi @tony359 

since I shall consider a difference between different models, I implemented following initial solution:
- There is a new parameter in the "Audio control" group of the application settings: "Master volume unit":
![Screenshot from 2024-08-30 15-59-40](https://github.com/user-attachments/assets/97687ed0-a43f-413b-8b26-c83c476fbc1c)

-  If you select this parameter, you will able to activate the indication in dB:
![Screenshot from 2024-08-30 16-02-05](https://github.com/user-attachments/assets/c777fc29-ab8e-4bed-8f70-f99693b19005)

- Initially, please leave "Zero (0 bB) level" parameter empty. In this case, the app will parse the receiver information message in order to define the maximum volume. If this message is not available for your model, the app will use the default value "82.0".

- If "Relative (dB) mode is active", the app shows the value in dB on the  LISTEN tab:
![Screenshot from 2024-08-30 16-05-46](https://github.com/user-attachments/assets/d467d311-36e4-40be-a3b7-8e9261187c1c)

... and in the "Audio control" window:
![Screenshot from 2024-08-30 16-06-41](https://github.com/user-attachments/assets/57a8ec41-842b-424a-946e-f8398fe73fcd)

Please download and manually install this APK:
https://1drv.ms/u/s!At2sh2-YDyGFg1TW0I3pm6ewnf4x

Please let me known whether it works for you as desired or not. If the value in dB is not correct, try to change "Zero (0 bB) level" parameter in the "Master volume unit" window.

**Comment by mkulesh** [comment]
Hi @tony359,

did you already tested the implementation of this feature?

**Comment by tony359** [comment]
Apologies, I haven't forgotten, just haven't had a chance. I shall test that ASAP!

Thanks!

**Comment by tony359** [comment]
Hello Mikhail,

I am somehow unable to download the shared file. It might be a onedrive issue (maybe temporary?). Can you confirm the link is still valid please? Apologies for taking so long.

**Comment by mkulesh** [comment]
Yes, it seems to be onedrive issue. Please take a look in the directory https://1drv.ms/f/s!At2sh2-YDyGFdsDFl6N3ncDowMg and try download MusicControl-v2.14.1-android.apk manually.

**Comment by tony359** [comment]
Thanks.
I've tested it now. Some notes.

- Out of the box, without manually adjusting the 0dB level, the level displayed by the app was incorrect by 30dB. I input "82" in the zero dB level and it works perfectly. All levels are matching.
- At least my Onkyo has 0.5 steps. The (+) and (-) adjustments on the app allows me to go through those 0.5dB steps but the app does not report the intermediate values. 
- When dragging the volume cursor with my finger, 1 time out of 5 (approx) the receiver would not change volume and the app would stay "out of sync". For example, both the app and AVR read -32dB, I drag to -20dB and everything works fine. But then I drag to -15dB, the app says -15dB but the AVR is still at -20dB. A subsequent change would work as normal. 

Thanks for now, I hope this helps! Let me know if there is anything I can to do help.

Cheers!

**Comment by mkulesh** [comment]
Hi @tony359,

thank you for testing. I have additional requests regarding your observations:

> Out of the box, without manually adjusting the 0dB level, the level displayed by the app was incorrect by 30dB. I input "82" in the zero dB level and it works perfectly. All levels are matching.

Strange since I use the data from the receiver information data provided by the device. Could you please collect this information as follows:
- Open Settings from the application menu
- Activate the "Developer options" on the end of the settings list
- Navigate to Application menu -> About -> Receiver information
- Press "Copy to clipboard"
- Create a text file and paste this information from clipboard into this file
- Send the file to me per email on mikhail.kulesh@gmail.com (Please do not attach this information here!)
- Switch OFF the "Developer options" in the settings

This information contains master volume parameters for your device that may help me to understand why the default 0dB level is invalid.

> At least my Onkyo has 0.5 steps. The (+) and (-) adjustments on the app allows me to go through those 0.5dB steps but the app does not report the intermediate values.

Could you please collect following information:
- Open Settings from the application menu
- Activate the "Developer options" on the end of the settings list
- Ensure that your device plays some music
- Close app
- Open the app again and open MEDIA tab, Wait 5 seconds.
- take a screenshot from the media tab where the current volume level is visible
- make one (+) adjustment (for example, using volume buttons on your smartphone)
- take a screenshot from the media tab again
- Navigate to Application menu -> About -> Latest logging
- Press "Copy to clipboard"
- Create a text file and paste this logging from the clipboard into this file
- Send this file to me per email with both screenshots
- Switch OFF the "Developer options" in the settings

This information allows me to inspect why intermediate values are incorrect

> When dragging the volume cursor with my finger, 1 time out of 5 (approx) the receiver would not change volume and the app would stay "out of sync". 

I also need the logging as follows
- Open Settings from the application menu
- Activate the "Developer options" on the end of the settings list
- Ensure that your device plays some music
- Close app
- Open the app again and open MEDIA tab, Wait 5 seconds.
- Drag the volume cursor with finger, until you observe the volume is "out of sync"
- take a screenshot from the media tab where the current volume level is visible
- Navigate to Application menu -> About -> Latest logging
- Press "Copy to clipboard"
- Create a text file and paste this logging from the clipboard into this file
- Send this file to me per email with the screenshot
- Switch OFF the "Developer options" in the settings

If you can please send me all required information in three separate emails with different topics since all three observations are independent...

**Comment by tony359** [comment]
Thanks

Can I ask what you mean with "play some music"? My Onkyo has two inputs: HDMI via PC or TOSlink from the TV. Would play some sound from those sources be ok?

Thanks

**Comment by mkulesh** [comment]
yes, correct, some sound from any input is enough...

**Comment by mkulesh** [comment]
Released in version 2.14.1
For premium version only
