### ISSUE TITLE
Power Button Coloring

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#32]
Because the power button is the same color if the device is on/off its hard to tell from the onpc the state of the device.  It would be nice if there was some type of visual indicator that the device is off (i.e. a greyed out button) or maybe the power button changes from greyed out to white or red to green?  Just need some visual indicator of device state.

**Comment by mkulesh** [comment]
Hi @mrlad, is is not too easy due to different themes. Now, I colored the power button using _accent theme color_ (that is different for each theme) if device is in standby mode. How does it look for you?
You can test it using the new version 0.9:
https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.9-debug.apk

**Comment by mrlad** [comment]
The visual indicator looks good.  Tried it with several different themes.

**Comment by mkulesh** [comment]
Released in version 0.9
