### ISSUE TITLE
Request: Better support for streamers

### ISSUE THREAD

**Issue by rdhughes** [mkulesh/onpc#323]
I have a Marantz SACD 30n SACD/Streamer/DAC and while this does see it and connects I can't seem to do anything with the device. There don't seem to be any options to add media, streaming services, DLNA server, etc.

**Comment by mkulesh** [comment]
Hi! The pure HEOS devices like Marantz  30n have a different network protocol, not the same like audio-video receivers (that is implemented in my app). Unfortunately, there is no documentation from Denon about this protocol. It means, some reverse engineering is necessary in order to support these devices. At the moment I have no such a device at home and therefore have no possibility to implement its support...
