### ISSUE TITLE
Problem with speaker toggle

### ISSUE THREAD

**Issue by quelbs** [mkulesh/onpc#50]
I am able to switch from A to B but then the toggle is stuck and I cannot proceed to A+B nor back to A.
A log file will follow via e-mail.

**Comment by mkulesh** [comment]
Hi @quelbs, 
there are already some development history for A/B speakers:
- I initially implemented it in issue #5 and released in version 0.6. This implementation was based on SPA(UP) and SPB(UP) commands:
`MessageChannel: >> sending: ISCP/v1[16,8]: SPB(UP)`
- Then I changed the implementation in #8 due to zone support since zone 2 does not support UP parameter and I shall use boolean state 00 or 01 instead:
 `MessageChannel: >> sending: ISCP/v1[16,8]: SPB(01)`
It is possible that this parameter only works for zone 2 and does not work for main zone like in your case
- Finally, I implemented "3-way toggle" in the #22

Could you please install the old version 0.6 (https://github.com/mkulesh/onpc/releases/download/v0.6/onpc-v0.6.apk) and test whether A/B speakers work in this version. If yes, I will just "revert" the implementation for main zone using SPA(UP)/SPB(UP) instead of SPA(01/00)/SPB(01/00)

**Comment by quelbs** [comment]
For me "SPA 00" and "SPA 01" work fine, the problem seems to be updating the current status (or better updating the button functionality and description).
After testing a bit more I figured out that refreshing the view (e.g. show settings - go back to Device panel) updates the current status text, afterwards I am able to change the setting again, but again only ONCE.

I could imagine that assigning the functionality to the button in the following lines of code causes the button to perform the same action when it is pressed multiple times, but does not update the button to perform another action on the second press:
https://github.com/mkulesh/onpc/blob/9e48f012eb356b2cefcd65e3503a7584b0a140ff/app/src/main/java/com/mkulesh/onpc/DeviceFragment.java#L218-L235

Maybe a drop-down list with the available options could be a solution? I actually expected these UI elements (for my receiver Dim level and Speaker setting) to be drop-down lists in the current UI. For me it was not intuitive for me that they are supposed to be toggle buttons.

**Comment by quelbs** [comment]
Thank you for fixing. It works for me now!

**Comment by mkulesh** [comment]
Released in version 1.0
