### ISSUE TITLE
Sound settings fall back to "direct"

### ISSUE THREAD

**Issue by WalterFaber** [mkulesh/onpc#69]
Hello!
First of all: Great App!!! Thank you very much!

Issue:
Sometimes, the sound settings of my R-N855 fall back to "direct" when I use the app even if I don't change the sound settings.
So far I wasn't able to reproduce the issue... however, I think it is related to Network issues. Sometimes, the app seems to hang (e.g. laggy response, loads only half of the information in the "play" screen). After that, I find the "direct" setting activated.

Please let me know if I can test something for you.

Thank you in advance!

**Comment by mkulesh** [comment]
Ho @WalterFaber,

thank you for feedback! The app has already a mechanism that allows to collect logging. If this problem can be observed sometime, you can activate this mechanism:
- Install the latest debug build from here: https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v1.2-debug.apk
- Open application settings and activate "Developer options". An application menu appears on the right of the toolbar. This menu contains the option "Latest logging"
- Use the app normally. When you observe if sound settings falls back to "direct" or  only a half of the information in the "play" screen, select this menu "Latest logging", than select all text from the loggimg dialog and send it me per e-mail. Do not publish this log here since it may contain MAC address or serial number of your receiver.

**Comment by mkulesh** [comment]
No response

**Comment by mkulesh** [comment]
Fixed and released in version 1.6
