### ISSUE TITLE
Add support for Zone 2

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#8]
My primary use case for this app is zone 2 (that is where I listen to the music server, Airplay, Pandora etc.).  Could you please consider adding support for zones (zone power on/off along with controlling the net sources that currently control zone 1)?

**Comment by mkulesh** [comment]
Hi @mrlad, thank you for submitting an issue. As I see in the documentation, there are only 7 zone-dependent commands used in the app:
- Power Command  (the button on toolbar)
- Speaker A/B Command (two-way switches in DEVICE tab)
- Muting and Volume Commands  (buttons in the volume control panel)
- Selector Command (input selectors in the MEDIA tab)
- Network Operation Command (playback control in the MONITOR tab)
- Listening Mode Command (mode selectors in the MONITOR tab)
It seems to be that the zone change affects the whole app. Do you have any idea how it shall be presented in the user interface? A switch in the app configuration that switches the whole app between available zones? Or maybe a new button in the app toolbar that shows all available zones (some receivers can have more than 2 zones) and allows to select one of them? Or, maybe, a standard navigation drawer opened with a "hamburger" button on the left of toolbar, where all available zones are shown and we can select one of them?

**Comment by mrlad** [comment]
Hi @mkulesh,

The Zone specific command list looks correct to me.  Personally, I use Power, mute & volume and the network & listening more commands but other users would utilize the other ones.

_Or, maybe, a standard navigation drawer opened with a "hamburger"_

I **think** that would be my initial preference.  Typically zone control is something you do once and then you don't want it cluttering the UI for a while until you're ready to change zones again.  The documentation I've see indicates up to three Zones on some Onkyo receivers.  My receiver supports 3 but I only utilize 2.

For non-technical users, unsure if the hamburger menu would be as intuitive as a toolbar menu button, but I think that would be slower for power users or those familiar with the app.

**Comment by mkulesh** [comment]
Hi @mrlad, 

Thank you for info. I totally agree, a standard navigation drawer is the best option. However, since I am not able to test any zone-specific functionally I suggest to solve this issue in two steps (in order to logically separate the network communication level from GUI):
- First step is just the protocol implementation. I will expand all zone-specific messages in order to support the zone that will be initially selected in the app settings screen.
- The second step, after the protocol will work as desired, I will move zone selection from app configuration into navigation drawer.   

Is this plan OK?

**Comment by mrlad** [comment]
Hi @mkulesh,

I like your rollout plan.  Thanks for considering supporting zones.

**Comment by mrlad** [comment]
Hi @mkulesh,

I tested out the nightly and here's my feedback:

1. **I was unable to install the nightly** over the play store app.  Had to uninstall that first.
2. **The app correctly detected that my receiver had zone 2 & 3**.
3. **I was able to set my active zone to zone 2** and it sticks every time the app is re-launched
4. **I was able to turn zone 2 off**.  I did this while AirPlay was playing (big mistake on my part).  Once I did that, I lost control of the net functionality on the device and had to reboot it.  I think this is an Onkyo bug.  I had this happen once before when I didn't shut down Airplay cleanly when it was playing in Zone 2.
5. **Volume controls only work on zone 1**.  Even though the active zone is set to zone 2, volume control continue to change zone 1 only.
6. **Media selections only work on zone 1**.  Even though the active zone is set to zone 2, changing a media type affects zone 1.

**Comment by mrlad** [comment]
Regarding Point #1 above...did you change the name of the app?  That might be the reason I had uninstall and then re-install.

**Comment by mkulesh** [comment]
Hi @mrlad, many thanks for feedback
- Point 1. Uninstall of play store version is necessary since play store is correctly signed, and the nightly build is not signed. 
- Point 4. I also think that it is the problem on onkyo site since this functionality is not yet implemented in the app
- Point 5,6: It is correct since I only implemented the Power Command in this build. 

I still developing other commands but need 2 or 3 days for it due to some time constraints.

**Comment by mrlad** [comment]
@mkulesh , I do appreciate the fast prototype.

**Comment by mkulesh** [comment]
Hi @mrlad, I introduced today zones for Muting and Volume Commands (three buttons in the volume control panel and the current volume level indication). I expect that all these three buttons and volume level indication shall work now for all available zones. Could you please test it?

![active_zone3](https://user-images.githubusercontent.com/30557348/52170137-0a448480-2745-11e9-8810-caae00f11c11.png)

**Comment by mrlad** [comment]
Hi @mkulesh ,

Can you please point me to the apk file with the nightly build so I can test it?

**Comment by mrlad** [comment]
Testing feedback:

Mute & volume control buttons work.  However, the reported volume level is wrong.  I'll open a new ticket on this because its wrong in Zone 1 too.

**Comment by mkulesh** [comment]
Hi @mrlad, in the latest autobuild, I now implemented the support of Selector Command in the MEDIA tab. Does it work?

**Comment by mkulesh** [comment]
Hi @mrlad, I am confused how playback control in the MONITOR tab shall work for different zones. In the protocol description I read "The Net-Tune/Network function is shared by the MAIN and ZONE side. But control is separated". The control pointed here is:
"PLAY" | PLAY KEY
"STOP" | STOP KEY
"PAUSE" | PAUSE KEY
"P/P" | PLAY / PAUSE KEY
"TRUP" | TRACK UP KEY
"TRDN" | TRACK DOWN KEY
"REP/SHF" | REPEAT / SHUFFLE KEY
Plus some iPod-relared control that is already obsolete (I tried my iPod 80Gb with my Onkyo networks player is see that iPod is not more supported)
Can you please describe how does this control work? Can you play two different tracks at the same time on two different zones? That happens with a track that being playing on main zone if you switch to zone 2 and press stop key? I just does not understand why play control is zone related...

**Comment by mrlad** [comment]
I looked through the manual, I don't have Speaker A/B functionality.  I suspect this is superceded by zone control.

**Comment by mrlad** [comment]
There is also a feature called whole house mode.  Do you see any documentation on that?  According to the manual, in whole house mode, all zones are set to the same media input.

**Comment by mkulesh** [comment]
Hi @mrlad 

> Changing a device in one zone will impact the other zone too.

Du you mean a network service like Deezer or Spotify or do you mean input selector like USB or NET? For example, can you play one track from USB on the main zone and, at the same time, an other track from  NET (for example, from Deezer) in zone 2?

> The selectors aren't working as expected. If I change zone 2 from NET to FM, Zone 1 changes to NET. Any change to zone 2 is changing the input on zone 1 also (but to something different than what I'm selecting in zone 2). The zone 2 selection actually works though.

It is very bad :( I have no idea why it happens. I just send one message SLZ for zone 2 as described in the documentation. Does the selector change for main zone (zone 1) works as expected?

In order to trace this problem I need receiver information message and application log from Android.
- receiver information can be collected in the app directly: please open "Settings" screen and activate "Developer options". If you closes "Settings" screen, a new item "Receiver Information" appears in the main menu. Please open this dialog, select whole XML presented there, and send me per e-mail (mikhail.kulesh@googlemail.com) or just push it as XML file in the directory https://github.com/mkulesh/onpc/tree/master/doc/ReceiverInformation
- Do you have ADB (Android Debug Bridge) or do you able to install it? If yes, collect the log as follows:
-- close the app
-- attach phone to PC where ADB is installed
-- ensure that you phone is detected by adb. Enter in console
`adb devices`
-- enter in console: 
`adb logcat -c`
-- enter in console: 
`adb logcat -s "onpc" > onpc.log`
-- start the app, select zone 2 and try all available input selectors in MEDIA tab
-- close the app
-- abort the log dumping (Ctrl+C in console where adb logcat is running)
-- email me this file onpc.log

I also noticed from the documentation that not all input selector are available in all zones. Today, I committed the code that shows input selectors only available in the actual zone (both in the settings screen as well as in the MEDIA tab). Can you observe all expected selectors for main zone and zone 2 or some selectors are missed?

**Comment by mrlad** [comment]
_Du you mean a network service like Deezer or Spotify or do you mean input selector like USB or NET?_

Input selector (NET, USB etc.)

_I just send one message SLZ for zone 2_

The code is behaving like the code code to communicate to zone 1 is being sent by accident also.

_Does the selector change for main zone (zone 1) works as expected?_

I believe so, but I'll have to double check.

_Does you receiver supports Listening Mode change for zone 2?_

The documentation doesn't mention zones with listening modes so I assume its zone independent.

**Comment by mrlad** [comment]
I captured the log, but before I sent it, I tried this scenario on the official app.  Zone 1 changes to NET when Zone 2 changes away from NET.  If I start onpc with zone 2 on something other than NET, I can change the zone 2 media input without affecting zone 1.  So this appears to either be a receiver bug or something that Onkyo/Integra consider to be working as designed.  Not sure at this point, but either way, its not an onpc bug.

**Comment by mrlad** [comment]
Changing zone 2 media inputs isn't something I do often..its always on NET for me.  Zone 1 is what changes all the time.  Hence, I never noticed this bug until I tried to test the new functionality.  

So now to try to find out if this is an receiver bug or working as designed.

**Comment by mrlad** [comment]
BTW, the https://github.com/PinBack23/nonkyo/releases project also supports multiple A/V receivers on the same subnet.  When it starts up, it shows you the available receivers.  Later on, you can force a re-scan for updated receivers.

**Comment by mkulesh** [comment]
Hi @mrlad, in any cases, the log from your receiver is interesting in order to understand how the zone works. I will appreciate if you send it t me.

I expanded now the OperationCommandMsg that is related to playback control from the MONITOR tab. Could you please test how this playback control works for both zones? It was the last message, i.e the communication level is fully implemented. As the next step, I will try to add navigation drawer and "hamburger" button.

If you think that NET behavior in Zone 1 is a bug maybe it is meaningful to ask the Onkyo support and reference the behavior of the the official app?

**Comment by mrlad** [comment]
I tested onpc on a different network tonight with a DTR 40.7 and a 30.7.  It was able to change the media selector in zone 2 without affecting zone 1.  So the problem I previously reported almost certainly is a receiver bug and not an onpc bug.

**Comment by mkulesh** [comment]
Hi @mrlad, Navigation drawer is now ready; i.e I moved zone selection from application settings into the Navigation drawer. All functions shall work now. I only plan to style navigation drawer a little bit, that shall have no impact on the zone functionality. If you have any ideas how to improve the design of the drawer, please let me known. 

![navigation_drawer](https://user-images.githubusercontent.com/30557348/52368541-fbb0e280-2a4e-11e9-9b96-77e918df0fe5.png)

**Comment by mrlad** [comment]
I like the initial implementation of the navigation drawer.  Very quick to change zones.

The official app has at the bottom of its zone selector a button to change the receiver (for those w/multiple receivers).  That's about the only other thing I could think would be useful in the drawer.

**Comment by mkulesh** [comment]
Hi @onschedule, there a issue with speakers for zone 2: The documentation says that Zone 2 A/B Command only have on/off commands whole main zone also has toggle command. The app sends sends toggle command that is not available for Zone 1. Will fix it.

**Comment by onschedule** [comment]
OK. My setup only utilizes A/B toggle for zone 2 anyway. I'll describe my
setup in case it helps you understand the environment in which I am testing
your great app.
Zone 1 is a 5.1 setup in my basement for movies where I also have a
projector and screen.
Zone 2A is my kitchen and Zone 2B is my living room where we watch TV
(these rooms are separated by a dining room with no line-of-sight).
When watching TV in living room, we often want to continue to listen to the
audio stream (the TV program's audio) when cooking or getting something to
eat. At other times, like when our daughter is watching something on living
room TV, we do not want its audio stream also in kitchen. Your app has
finally provided a solution here!!! Until now, we were not able to silence
kitchen audio during times we did not want it.

I was able to duplicate the bug. When doing the following, Zone 2 is turned
off into standby:
While playing music on Zone 2 with both A and B set to "on" I turned off A
and then turned off B. There is really no reason why anyone should want to
do this in the real world- they would just use mute. But still it could be
done by accident and then a hassle to have to turn the zone power back on
and restart whatever audio was running...  Maybe you could prevent both
from being turned off... If A is already off, prevent B from being also
turned off? And if B is already off prevent A from being turned off...
Again- wonderful wonderful app!

**Comment by mkulesh** [comment]
Released in v0.7

**Comment by mrlad** [comment]
Confirmed fixed.
