### ISSUE TITLE
Cannot control CD Player over RI

### ISSUE THREAD

**Issue by MartinHignett** [mkulesh/onpc#81]
Hi! Thanks for a great app! I have a small issue, however:

I have an Onkyo CD Player C-7030 CD Player connected via RI to my Onkyo TX-8270. The app works great with TX-8270, but I can't control the CD player. I enabled the RI & CD Player options in the menu and I can see the CD player device under the RI tab. However, nothing happens when I click on anything.

The RI integration between the TX-8270 and CD player seems to be OK - I can control the CD player using the TX-8270 remote control.

Any ideas what I might be doing wrong? I've a feeling there's an option I have to set somewhere...

Thanks!

**Comment by mkulesh** [comment]
Hi @MartinHignett, the problem with TX-8270 is that this receiver does not support CD player via network protocol. The CD player is only supported via remote control. Please activate the developer options in the app and then open the dialog "Receiver Information" from main menu (three dots in toolbar). You will see the technical information about your receiver. The RI support is given in the section 
`<controllist count="61">
...
            <control id="AMP Control(RI)" value="0" />
            <control id="CD Control(RI)" value="0" />
            <control id="CD Control" value="0" />
            <control id="BD Control(CEC)" value="1" />
            <control id="TV Control(CEC)" value="1" />
...
</controllist>
`
the value 0 means that this feature is programmatically deactivated in the receiver firmware (I think Onkyo do it from a marketing reason) and value 1 means this feature is resented. For you model, you only have  BD and TV Control via CEC.

But, again, this configuration only describes the network protocol. The standard remote control works independently from this protocol.

I think I just shall to consider  "AMP Control(RI)" and "CD Control(RI)" parameters in order to enable/disable these features in the app. That do you think?

**Comment by mkulesh** [comment]
Consider "AMP Control(RI)" and "CD Control(RI)" parameters in order to enable/disable RI tab

**Comment by MartinHignett** [comment]
Ah, that's a shame. Thanks for the information. I wonder if they'll ever patch that?
