### ISSUE TITLE
Onkyo C-N7050

### ISSUE THREAD

**Issue by pagiraud** [mkulesh/onpc#82]
I own an Onkyo C-N7050. It works with the Onkyo app or any DLNA app (only for the DLNA part, of course) but it I can't connect to it with this app, even by entering the IP address manually.
Is this normal or is this a bug ?
Edit : I activated the developer options and opened the Receiver Information dialog : it is empty.

**Comment by mkulesh** [comment]
Hi @pagiraud, 
yes it is possible that the modern CD players are not supported by my app. The app does not support DLNA. Instead of it, the app is based on Onkyo ISCP protocol (available on port 60128 of the receiver). It you player does not have this protocol or the port is 60128 is not available, the app can not connect ti such a device. 
Could you test with nmap which ports are open on your player like 
`nmap -sS -p0-65535 -T5 <IP_ADDRESS>`
the output shall be like this:
`PORT      STATE SERVICE
80/tcp    open  http
4545/tcp  open  worldscores
5000/tcp  open  upnp
8008/tcp  open  http
8009/tcp  open  ajp13
8080/tcp  open  http-proxy
8888/tcp  open  sun-answerbook
10001/tcp open  scp-config
60128/tcp open  unknown
`
The question is whether 60128 is open?

**Comment by pagiraud** [comment]
Yes, it is open :
PORT      STATE SERVICE
80/tcp    open  http
8888/tcp  open  sun-answerbook
60128/tcp open  unknown

**Comment by mkulesh** [comment]
Could you please install the latest debug build from here: https://github.com/mkulesh/onpc/blob/autobuild/autobuild/onpc-v1.3-release.apk

After installing this version, please activate the developer options and ensure that you phone and your CD player are in the same WLAN. Try to connect manually by putting the IP of player and port 60128 in the "Connect dialog". After it, open the dialog "Latest logging" from main menu, select whole text and send it me per Email (mikhail.kulesh@gmail.com)

**Comment by pagiraud** [comment]
Ok, I just did it.

**Comment by mkulesh** [comment]
It seems to be C-N7050 ignores all requests sent by ISCP protocol. Instead of it, C-N7050 has official DLNA support and supports "Onkyo Remote App". Currently, my app can not work with C-N7050 since DLNA support is missed in my app.

**Comment by mkulesh** [comment]
C-N7050 can not be supported
