### ISSUE TITLE
Give option to use Friendly Name for Media Inputs

### ISSUE THREAD

**Issue by mrlad** [mkulesh/onpc#9]
Could you please give us the option in settings to show the friendly name that is mapped to the default media input?

For example, I've mapped 

- Bluray to the BD/DVD input 
- HTPC to the PC input etc

**Comment by mkulesh** [comment]
Hi @mrlad, for the media inputs, there are two name version:

- On the one hand, some names are provided by Onkyo device in the ReceiverInformation message (see for example https://github.com/mkulesh/onpc/blob/master/doc/ReceiverInformation-TX-NR676E.xml). I do not use these names in the app
- Instead of it, I defined string constants in the file https://github.com/mkulesh/onpc/blob/master/app/src/main/res/values/strings.xml for all inputs known from the protocol description.
    
    <string name="input_selector_video1">VCR/DVR</string>
    <string name="input_selector_video2">CBL/SAT</string>
    <string name="input_selector_video3">GAME</string>
    <string name="input_selector_video4">AUX</string>
 These constants are used in the app.

The simplest way is just improve the text for these constants.

Or do you mean a king of editor where some "alternative" names can be given for all these inputs?

**Comment by mrlad** [comment]
Hi @mkulesh,

_some names are provided by Onkyo device in the ReceiverInformation message_

Yes, those are the standard default names.

_The simplest way is just improve the text for these constants_

Don't think this solves the problem.  Many users will have unique names/setups and no matter how descriptive you make it, you'll never be able to solve everyone's configuration.  

_Or do you mean a king of editor where some "alternative" names_

No. The Integra setup lets you rename the input to a friendly name.  These are the alternate names I'm referring to.

The cleanest solution is to pull the friendly name from the receiver.  The official Integra Remote 3 app is able to pull the friendly name from the receiver and display it so it is possible via the API.

**Comment by mkulesh** [comment]
Hi @mrlad, thank you for explanation. Do you propose just replace in-app string resources by the names provided in the ReceiverInformation message or add application setting like "Use input selector names from receiver"?

**Comment by mrlad** [comment]
Hi @mkulesh ,

I think having an application setting is the best approach.  Some people may not want to use the friendly name.  Although to be honest, if they created a friendly name I'm not sure why they wouldn't want to see it by default, but inevitably, someone won't want to see it so a setting should make everyone happy.

**Comment by mkulesh** [comment]
Hi @mrlad,
I added new two-way switch into the "Device input selector" setting screen. It it is switched-on (default setting), than the names provided by Onkyo device will be used in the MEDIA tab instead of build-in names. The setting screen itself is not changed - I still use here the build-in names. Could you please test it with the latest autobuild from https://github.com/mkulesh/onpc/raw/autobuild/autobuild/onpc-v0.7.apk?

![friendly_selector_name](https://user-images.githubusercontent.com/30557348/52176980-f76c9700-27ba-11e9-9950-871b31e190b1.png)

**Comment by mrlad** [comment]
Hi @mkulesh, changing this selection caused the friendly name to show under the Media but it didn't change the name shown in settings.  This is working as you'd expect in this test drop correct?

**Comment by mkulesh** [comment]
Hi @mrlad, you are right, I expected no changes for the name shown in settings. Yesterday... Today, howeve, the "Input Selectors" setting screen is also expanded and now, if you changes "Friendly selector name" switch, the names in this settings screen shall also be adapted. I hope this issue is now fully implemented. Please re-test using the latest build it and close the issue if everything is OK.

**Comment by mkulesh** [comment]
Released in v0.7

**Comment by mrlad** [comment]
Confirmed fixed.
